##2015-11-5
alter table FC_STATISTICS_WITHDRAW_TIME add key STATISTICS_END_TIME_KEY(STATISTICS_END_TIME);
alter table FC_IMAGE_VARIFY add key ORDER_NO_KEY(ORDER_NO);
alter table FC_LOAD_AUDIT_RECORD ADD KEY ACCOUNT_CHANGE_TIME_KEY(ACCOUNT_CHANGE_TIME);
alter table FC_WITHDRAW_TRANSIT_DETAIL ADD KEY PAY_BANK_NO_KEY(PAY_BANK_NO);
