use fcpay;

DROP TABLE if exists FC_STATISTICS_WITHDRAW_DAY;
CREATE
    TABLE FC_STATISTICS_WITHDRAW_DAY
    (
        STATISTICS_ID CHAR(38) NOT NULL COMMENT '统计ID',
        STATISTICS_DAY CHAR(10) COMMENT '时间日',
        BUSINESS_ID VARCHAR(32) COMMENT '所属平台',
        WITHDRAW_NUM INT COMMENT '提现数量',
        WITHDRAW_AMD DECIMAL(16,4) COMMENT '提现金额',
        TOTAL_TIME VARCHAR(32) COMMENT '每笔作业总时间',
        TOTAL_DELAY_RATE DECIMAL(16,4) COMMENT '总时间延迟率',
        RISK_TIME VARCHAR(32) COMMENT '每笔风控作业时间',
        RISK_VIEW_TIME VARCHAR(32) COMMENT '每笔风控初审作业时间',
        RISK_REVIEW_TIME VARCHAR(32) COMMENT '每笔风控复审作业时间',
        RISK_DELAY_RATE DECIMAL(16,4) COMMENT '风控延迟率',
        OPERATION_TIME VARCHAR(32) COMMENT '每笔运营作业时间',
        OPERATE_ONE_TIME VARCHAR(32) COMMENT '运营一级特批时间',
        OPERATE_TWO_TIME VARCHAR(32) COMMENT '运营二级特批时间',
        OPERATION_DELAY_RATE DECIMAL(16,4) COMMENT '运营延迟率',
        FINANCE_TIME VARCHAR(32) COMMENT '每笔财务作业时间',
        FINANCE_DELAY_RATE DECIMAL(16,4) COMMENT '财务作业时间延迟率',
        LOAN_TIME VARCHAR(32) COMMENT '每笔放款作业时间',
        AUTO_LOAN_TIME VARCHAR(32) COMMENT '全自动放款时间',
        SEMIAUTO_LOAN_TIME VARCHAR(32) COMMENT '半自动放款时间',
        LOAN_ROBOT_TIME VARCHAR(32) COMMENT '放款机器人时间',
        LOAN_ERROR_TIME VARCHAR(32) COMMENT '异常放款时间',
        LABOUR_LOAN_TIME VARCHAR(32) COMMENT '人工放款时间',
        LOAN_DELAY_RATE DECIMAL(16,4) COMMENT '资管延迟率',
        AUTO_TRANS_TIME VARCHAR(32) COMMENT '全自动出款时间（等卡）',
        SEMIAUTO_TRANS_TIME VARCHAR(32) COMMENT '半自动出款时间',
        TRANS_ROBOT_TIME VARCHAR(32) COMMENT '出款机器人时间',
        TRANS_ERROR_TIME VARCHAR(32) COMMENT '出款异常时间',
        LABOUR_TRANS_TIME VARCHAR(32) COMMENT '人工出款时间',
        TRANSIT_TIME VARCHAR(32) COMMENT '每笔出款作业时间',
        TRANSIT_DELAY_RATE DECIMAL(16,4) COMMENT '结算延迟率',
        KEEP_ONE_TIME VARCHAR(32) COMMENT '预留一',
        KEEP_TWO_TIME VARCHAR(32) COMMENT '预留二',
        KEEP_THREE_TIME VARCHAR(32) COMMENT '预留三',
        PRIMARY KEY (STATISTICS_ID)
    ) DEFAULT CHARSET=utf8;