use fcpay;

alter table FC_INNERC_ACCOUNT modify ACCOUNT_NO VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '账户号';

drop table if exists FC_INNERC_ACCOUNT_EXTRA;
CREATE
    TABLE FC_INNERC_ACCOUNT_EXTRA
    (
        ACCOUNT_ALIAS CHAR(38) NOT NULL,
        DAY_PAY_MONEY DECIMAL,
        MONTH_PAY_MONEY DECIMAL,
        LAST_UPDATE_TIME DATETIME,
        ACCOUNT_TYPE INT COMMENT '充值渠道(1银行 2第三方支付)',
        PRIMARY KEY (ACCOUNT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists FC_INNERC_BINDED_ACCOUNT;
CREATE
    TABLE FC_INNERC_BINDED_ACCOUNT
    (
        BIND_ID VARCHAR(64) NOT NULL,
        ACCOUNT_ALIAS CHAR(38) NOT NULL,
        BIND_BANK_CARD_ALIAS CHAR(38) NOT NULL,
        STATUS INT,
        LAST_UPDATE_TIME DATETIME,
        COMMENTS VARCHAR(1024),
        PRIMARY KEY (BIND_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists FC_INNERC_PAYMENT_ACCOUNT_BANK;
CREATE
    TABLE `FC_INNERC_PAYMENT_ACCOUNT_BANK`
    (
        `PAYMENT_BANK_ID` CHAR(38) NOT NULL COMMENT '流水號',
        `PAYMENT_CHANNEL_ID` CHAR(38) DEFAULT NULL,
        `BANK_NAME` VARCHAR(20) DEFAULT NULL COMMENT '銀行名稱',
        `BANK_CODE` VARCHAR(15) DEFAULT NULL COMMENT '银行代码',
        `STATUS` INT(11) DEFAULT NULL COMMENT '狀態(1.f啟用0.停用)',
        `MODIFY_TIME` DATETIME DEFAULT NULL,
        `CREATE_TIME` DATETIME DEFAULT NULL,
        `BANK_VALUE` VARCHAR(15) DEFAULT NULL COMMENT '銀行值',
        PRIMARY KEY (`PAYMENT_BANK_ID`)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists FC_INNERC_PAYMENT_BANK_DEPLOY;
CREATE
    TABLE `FC_INNERC_PAYMENT_BANK_DEPLOY`
    (
        `DEPLOY_ID` CHAR(38) NOT NULL COMMENT '流水號',
        `BUSINESS_ID` CHAR(64) DEFAULT NULL COMMENT '游戏平台',
        `DEPLOY_CODE` VARCHAR(30) DEFAULT NULL COMMENT '配置代號',
        `DEPLOY_VALUE` VARCHAR(30) DEFAULT NULL COMMENT '配置值',
        `PAYMENT_ID` CHAR(38) DEFAULT NULL,
        `PAYMENT_BANK_ID` CHAR(38) DEFAULT NULL COMMENT '流水號',
        `ACCOUNT_ALIAS` CHAR(38) DEFAULT NULL,
        `STATUS` INT(11) DEFAULT NULL COMMENT '啟用(1)停用(0)',
        `CREATE_BY` VARCHAR(20) DEFAULT NULL,
        `CREATE_TIME` DATETIME DEFAULT NULL,
        `MODIFIED_BY` VARCHAR(20) DEFAULT NULL,
        `MODIFIED_TIME` DATETIME DEFAULT NULL,
        PRIMARY KEY (`DEPLOY_ID`)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists FC_NOTIFICATION;
CREATE
    TABLE `FC_NOTIFICATION`
    (
        `FC_NOTIFICATION_ID` CHAR(38) NOT NULL COMMENT '通知ID',
        `BUSINESS_ID` CHAR(38) DEFAULT NULL COMMENT '业务平台',
        `NT_TITLE` VARCHAR(30) NOT NULL COMMENT '标题',
        `NT_MESSAGE` VARCHAR(1024) NOT NULL COMMENT '讯息(可存取html)',
        `NT_BIND_TYPE` INT(11) NOT NULL COMMENT '绑定权限范围的类型 1 userName   2 roleName   3 menuName   4 modelName',
        `NT_BIND_VALUE` CHAR(30) NOT NULL COMMENT '绑定权限范围的值 如type是1 value为admin, type为2 value为2010, type为3 value为10006, type为4 value为monitor',
        `IS_READ` TINYINT(1) DEFAULT NULL COMMENT '是否已读',
        `IS_PUBLISH` TINYINT(1) DEFAULT NULL COMMENT '是否发布',
        `NT_LEVEL` VARCHAR(50) DEFAULT NULL COMMENT '日志级别(INFO,ERROR,WARING,EMERGENCY,SUCCESS)',
        `NT_START_TIME` DATETIME DEFAULT NULL COMMENT '开始时间',
        `NT_END_TIME` DATETIME DEFAULT NULL COMMENT '结束时间',
        `HOST_IP` VARCHAR(15) DEFAULT NULL COMMENT '來源位置',
        `CREATOR` VARCHAR(50) NOT NULL COMMENT '建立者',
        `CREATE_TIME` DATETIME NOT NULL COMMENT '建立时间',
        `MODIFIER` VARCHAR(50) NOT NULL COMMENT '修改者',
        `MODIFY_TIME` DATETIME NOT NULL COMMENT '修改时间',
        PRIMARY KEY (`FC_NOTIFICATION_ID`)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists FC_PAY_FROM_GOPAY;
CREATE
    TABLE FC_PAY_FROM_GOPAY
    (
        FC_ORDER_NO VARCHAR(32) NOT NULL COMMENT '?????ID',
        VERSION VARCHAR(5),
        CHARSET VARCHAR(1),
        LANGUAGE VARCHAR(1),
        SIGN_TYPE VARCHAR(1),
        TRAN_CODE VARCHAR(4),
        MER_CHANT_ID VARCHAR(10),
        MER_ORDER_NUM VARCHAR(30),
        TRAN_AMT VARCHAR(12),
        FEE_AMT VARCHAR(12),
        FRONT_MER_URL VARCHAR(256),
        BACKGROUND_MER_URL VARCHAR(256),
        TRAN_DATE_TIME VARCHAR(14),
        TRAN_IP VARCHAR(19),
        RESP_CODE VARCHAR(6),
        MSG_EXT VARCHAR(1024),
        ORDER_ID VARCHAR(16),
        GOPAY_OUTORDER_ID VARCHAR(32),
        BANK_CODE VARCHAR(10),
        TRAN_FINISH_TIME VARCHAR(14),
        GOODS_NAME VARCHAR(200),
        GOODS_DETAIL VARCHAR(1000),
        BUYER_NAME VARCHAR(50),
        BUYER_CONTACT VARCHAR(200),
        MER_REMARK_1 VARCHAR(500),
        MER_REMARK_2 VARCHAR(500),
        SIGN_VALUE VARCHAR(1024),
        PRIMARY KEY (FC_ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists FC_PAY_FROM_OFFBANK;
CREATE
    TABLE `FC_PAY_FROM_OFFBANK`
    (
        `FC_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '給银行充值的ID',
        `DATA_NO` VARCHAR(32) DEFAULT NULL COMMENT '流水号',
        `DEPOSIT_APPLY_ID` VARCHAR(32) DEFAULT NULL COMMENT '充值申请流水号',
        `USER_NAME` VARCHAR(32) DEFAULT NULL COMMENT '会员账号',
        `STATUS` INT(11) DEFAULT NULL COMMENT '上分状态',
        `AMOUNT` DECIMAL(10,0) DEFAULT NULL COMMENT '充值金额',
        `CHARGE` DECIMAL(10,0) DEFAULT NULL COMMENT '手续费',
        `COMMENTS` VARCHAR(128) DEFAULT NULL COMMENT '上分结果描述',
        PRIMARY KEY (`FC_ORDER_NO`)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists FC_PAY_TO_GOPAY;
CREATE TABLE `FC_PAY_TO_GOPAY` (
  `FC_MESSAGE_NO` char(38) NOT NULL COMMENT '发送命令号',
  `VERSION` varchar(5) DEFAULT NULL,
  `LANGUAGE` varchar(1) DEFAULT NULL,
  `TRAN_CODE` varchar(4) DEFAULT NULL,
  `FEE_AMT` varchar(12) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(3) DEFAULT NULL,
  `TRAN_DATE_TIME` varchar(14) DEFAULT NULL,
  `VIR_CARD_NO_IN` varchar(19) DEFAULT NULL,
  `TRAN_IP` varchar(19) DEFAULT NULL,
  `IS_REPEATSUBMIT` varchar(1) DEFAULT NULL,
  `GOODS_NAME` varchar(200) DEFAULT NULL,
  `GOODS_DETAIL` varchar(1000) DEFAULT NULL,
  `BUYER_NAME` varchar(50) DEFAULT NULL,
  `BUYER_CONTACT` varchar(200) DEFAULT NULL,
  `MER_REMARK_1` varchar(500) DEFAULT NULL,
  `MER_REMARK_2` varchar(500) DEFAULT NULL,
  `GOPAY_SERVER_TIME` varchar(14) DEFAULT NULL,
  `BANK_CODE` varchar(10) DEFAULT NULL,
  `USER_TYPE` varchar(1) DEFAULT NULL,
  `SIGN_VALUE` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`FC_MESSAGE_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists FC_PAY_TO_OFFBANK;
CREATE TABLE `FC_PAY_TO_OFFBANK` (
  `FC_MESSAGE_NO` char(38) NOT NULL COMMENT '发送命令号',
  `DATA_NO` varchar(32) NOT NULL COMMENT '流水号',
  `DEPOSIT_APPLY_ID` varchar(32) NOT NULL COMMENT '充值申请流水号',
  `USER_NAME` varchar(32) NOT NULL COMMENT '会员名',
  `CHANNEL_TYPE` int(11) NOT NULL COMMENT '充值渠道',
  `CHANNEL_NAME` varchar(50) NOT NULL COMMENT '渠道名称',
  `DEPOSIT_NO` varchar(50) DEFAULT NULL COMMENT '充值账号',
  `DEPOSIT_NAME` varchar(32) DEFAULT NULL COMMENT '充值姓名',
  `RECEIPT_NO` varchar(32) DEFAULT NULL COMMENT '收款账户',
  `AGENT` varchar(32) NOT NULL COMMENT '上级代理',
  `AMOUNT` decimal(10,0) NOT NULL COMMENT '充值申请金额',
  `DEPOSIT_APPLY_TIME` datetime NOT NULL COMMENT '申请充值时间',
  `APPLY_COMMENTS` varchar(128) NOT NULL COMMENT '附言',
  PRIMARY KEY (`FC_MESSAGE_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



alter table FC_SYS_PARAMETER modify PARAMETER_CODE VARCHAR(50) COLLATE utf8_bin NOT NULL;
alter table FC_SYS_PARAMETER modify PARAMETER_NAME VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL;
alter table FC_SYS_PARAMETER modify PARAMETER_VALUE VARCHAR(100) COLLATE utf8_bin NOT NULL;
alter table FC_SYS_PARAMETER add BUSINESS_ID CHAR(38) COLLATE utf8_unicode_ci NOT NULL;

update FC_SYS_PARAMETER set BUSINESS_ID = 'JXC';



