ALTER TABLE fcpay.FC_WITHDRAW_APPLY ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_WITHDRAW_APPLY ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_WITHDRAW_APPLY ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_WITHDRAW_APPLY ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_WITHDRAW_APPLY ADD KEY dml_time_key(dml_time);



ALTER TABLE fcpay.FC_WITHDRAW_LOAN_DETAIL ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_WITHDRAW_LOAN_DETAIL ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_WITHDRAW_LOAN_DETAIL ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_WITHDRAW_LOAN_DETAIL ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_WITHDRAW_LOAN_DETAIL ADD KEY dml_time_key(dml_time);

ALTER TABLE fcpay.FC_WITHDRAW_TRANSIT_DETAIL ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_WITHDRAW_TRANSIT_DETAIL ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_WITHDRAW_TRANSIT_DETAIL ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_WITHDRAW_TRANSIT_DETAIL ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_WITHDRAW_TRANSIT_DETAIL ADD KEY dml_time_key(dml_time);


ALTER TABLE fcpay.FC_WEB_GAME_TRADE ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_WEB_GAME_TRADE ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_WEB_GAME_TRADE ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_WEB_GAME_TRADE ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_WEB_GAME_TRADE ADD KEY dml_time_key(dml_time);


ALTER TABLE fcpay.FC_BANKMSG_ASSISTANT_TO_WEB ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_BANKMSG_ASSISTANT_TO_WEB ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_BANKMSG_ASSISTANT_TO_WEB ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_BANKMSG_ASSISTANT_TO_WEB ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_BANKMSG_ASSISTANT_TO_WEB ADD KEY dml_time_key(dml_time);


ALTER TABLE fcpay.FC_BANKMSG_WEB_TO_ASSISTANT ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_BANKMSG_WEB_TO_ASSISTANT ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_BANKMSG_WEB_TO_ASSISTANT ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_BANKMSG_WEB_TO_ASSISTANT ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_BANKMSG_WEB_TO_ASSISTANT ADD KEY dml_time_key(dml_time);


ALTER TABLE fcpay.FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO ADD KEY dml_time_key(dml_time);


ALTER TABLE fcpay.FC_RISK_GAME_FLOW_DETAIL ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_RISK_GAME_FLOW_DETAIL ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_RISK_GAME_FLOW_DETAIL ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_RISK_GAME_FLOW_DETAIL ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_RISK_GAME_FLOW_DETAIL ADD KEY dml_time_key(dml_time);


ALTER TABLE fcpay.FC_RISK_GAME_WINNING_INFO ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_RISK_GAME_WINNING_INFO ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_RISK_GAME_WINNING_INFO ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_RISK_GAME_WINNING_INFO ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_RISK_GAME_WINNING_INFO ADD KEY dml_time_key(dml_time);


ALTER TABLE fcpay.FC_RISK_GAME_WINNING_INFO ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_RISK_GAME_WINNING_INFO ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_RISK_GAME_WINNING_INFO ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_RISK_GAME_WINNING_INFO ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_RISK_GAME_WINNING_INFO ADD KEY dml_time_key(dml_time);


ALTER TABLE fcpay.FC_RISK_CUSTOMER_ACCOUNT_INFO ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_RISK_CUSTOMER_ACCOUNT_INFO ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_RISK_CUSTOMER_ACCOUNT_INFO ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_RISK_CUSTOMER_ACCOUNT_INFO ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_RISK_CUSTOMER_ACCOUNT_INFO ADD KEY dml_time_key(dml_time);

ALTER TABLE fcpay.FC_WITHDRAW_LOAN_APPLY_REF ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE fcpay.FC_WITHDRAW_LOAN_APPLY_REF ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE fcpay.FC_WITHDRAW_LOAN_APPLY_REF ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE fcpay.FC_WITHDRAW_LOAN_APPLY_REF ADD KEY init_time_key(init_time);
ALTER TABLE fcpay.FC_WITHDRAW_LOAN_APPLY_REF ADD KEY dml_time_key(dml_time);


ALTER TABLE npe.tasks ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE npe.tasks ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE npe.tasks ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE npe.tasks ADD KEY init_time_key(init_time);
ALTER TABLE npe.tasks ADD KEY dml_time_key(dml_time);


ALTER TABLE npe.oplogs ADD `init_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间';
ALTER TABLE npe.oplogs ADD `dml_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间';
ALTER TABLE npe.oplogs ADD `dml_flag` tinyint NOT NULL DEFAULT '1' COMMENT '数据操作标识: 1-新增;2-修改;3-删除';
ALTER TABLE npe.oplogs ADD KEY init_time_key(init_time);
ALTER TABLE npe.oplogs ADD KEY dml_time_key(dml_time);

