use fc_wfc;
DROP TABLE
    FC_PAY_FROM_SF;
CREATE TABLE
    FC_PAY_FROM_SF
    (
        FC_ORDER_NO VARCHAR(32) NOT NULL COMMENT '給新生的ID',
        PAY_ORDER_NO VARCHAR(50) COMMENT '系统订单号',
        MER_CHANT_ID VARCHAR(12) COMMENT '商户ID',
        MER_ORDER_NO VARCHAR(32) COMMENT '商户订单号',
        CARD_NO VARCHAR(12),
        CARD_TYPE VARCHAR(4),
        FACT_MONEY VARCHAR(10),
        PAY_RESULT VARCHAR(10),
        CUSTOMIZE_A VARCHAR(255),
        CUSTOMIZE_B VARCHAR(255),
        CUSTOMIZE_C VARCHAR(255),
        PAY_TIME VARCHAR(30),
        ERROR_MSG VARCHAR(255),
        SIGN VARCHAR(100),
        PRIMARY KEY (FC_ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE
    FC_PAY_TO_SF;
CREATE TABLE
    FC_PAY_TO_SF
    (
        FC_MESSAGE_NO CHAR(38) NOT NULL COMMENT '发送命令号',
        CARD_TYPE VARCHAR(4) COMMENT '商品代码,15=网银, 16=盛付通卡',
        BANK_ID VARCHAR(12) COMMENT '银行代码',
        CUSTOMIZE_A VARCHAR(255) COMMENT '自定义A, 通知时原样返回',
        CUSTOMIZE_B VARCHAR(255) COMMENT '自定义B, 通知时原样返回',
        CUSTOMIZE_C VARCHAR(255) COMMENT '自定义C, 通知时原样返回',
        PRIMARY KEY (FC_MESSAGE_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;