use fcpay;

drop table if exists FC_INNERC_MONITOR_ORDER;
CREATE
    TABLE FC_INNERC_MONITOR_ORDER
    (
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '卡别名',
        STATUS INT(1) COMMENT '完成状态0，未完成，1完成',
        CREATE_TIME DATETIME COMMENT '创建时间',
        OPERATOR VARCHAR(64) COLLATE utf8_bin COMMENT '操作员',
        PRIMARY KEY (ACCOUNT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='该表记录是监控 登陆时发送指令状态的表';

drop table if exists   FC_INNERC_BALANCE;
CREATE
    TABLE FC_INNERC_BALANCE
    (
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        ACCOUNT_BALANCE DECIMAL(16,4) COMMENT '银行余额',
        ACCOUNT_BALANCE_UPDTIME DATETIME COMMENT '银行余额更新时间',
        TEMP_BALANCE DECIMAL(16,4) COMMENT '业务余额',
        TEMP_BALANCE_UPDTIME DATETIME COMMENT '业务余额更新时间',
        REQMONEY_TYPE INT COMMENT '请款标示:0 请款中  1 ,无请款',
        RESERVED1 VARCHAR(64) COLLATE utf8_bin,
        RESERVED2 VARCHAR(64) COLLATE utf8_bin,
        PRIMARY KEY (ACCOUNT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='银行卡实时余额表，每次银行返还余额信息更新，交易也更新';

drop table if exists  FC_INNERC_LEDGER_RECORD;
CREATE
    TABLE FC_INNERC_LEDGER_RECORD
    (
        RECORD_ID CHAR(38) NOT NULL COMMENT '记录ID',
        ACCOUNT_ALIAS CHAR(38) NOT NULL COMMENT '账户编号',
        RECORD_DAY VARCHAR(20) NOT NULL COMMENT '日期',
        RECEIPTS DECIMAL(16,4) COMMENT '当日总收入',
        EXPENDITURE DECIMAL(16,4) COMMENT '当日总支出',
        RECEIPTS_NUM INT COMMENT '当日总收入条数',
        EXPENDITURE_NUM INT COMMENT '当日总支出条数',
        UPDATE_DATE DATETIME COMMENT '最后更新时间',
        BUSINESS_ID CHAR(64) COMMENT '平台编码',
        ACCOUNT_AUTO_TYPE VARCHAR(20) COMMENT '账户层级描述',
        PRIMARY KEY (RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='当日总账表,按天记录所有卡的总收入和总支出';

 drop table if exists  FC_LOAD_AUDIT_BATCH_RECORD;
CREATE
    TABLE FC_LOAD_AUDIT_BATCH_RECORD
    (
        PREPAID_ACCOUNT_CHANGE_INFO_ID CHAR(38) NOT NULL COMMENT '流水号',
        INFO_ID CHAR(38) COMMENT '流水号',
        BUSINESS_ID CHAR(64) COMMENT '平台编码',
        ACCOUNT_CHANGE_ID VARCHAR(60) NOT NULL COMMENT '充值账变流水号',
        ACCOUNT_CHANGE_TIME DATETIME NOT NULL COMMENT '账变时间',
        ACCOUNT_CHANGE_TYPE VARCHAR(100) NOT NULL COMMENT '账变类型',
        ACCOUNT_CHANGE_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '账变金额',
        AVAILABLE_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '可用余额',
        IP_ADDRESS CHAR(30) NOT NULL COMMENT '网络地址',
        ACCOUNT_NO_REMARK VARCHAR(512) COMMENT '卡号备注',
        LOAD_TYPE INT NOT NULL COMMENT '上分类型(0 自动上分 1 手动上分)',
        REMARK VARCHAR(512) COMMENT '备注',
        ORDER_ID VARCHAR(64) COMMENT '第三方订单号',
        CHANNEL_TYPE CHAR(1) COMMENT '渠道 (1.银行2.第三方)',
        CHANNEL_NAME VARCHAR(32) COMMENT '渠道名称(NP新生IPS环迅 SF顺峰,ICBC,ABC..)',
        USER_NAME VARCHAR(32) COMMENT '用户名',
        AGENT VARCHAR(32) COMMENT '所属总代',
        LOAD_STATUS INT COMMENT '充值验证状态',
        LAST_UPDATE_TIME DATETIME NOT NULL COMMENT '最後更新时间',
        CREATE_TIME DATETIME COMMENT '建立时间',
        OPR_COMMENT VARCHAR(255) COMMENT '操作原因',
        OPERATOR VARCHAR(32) COMMENT '操作者',
        PRIMARY KEY (PREPAID_ACCOUNT_CHANGE_INFO_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists   FC_LOAD_AUDIT_BATCH_RECORD_INFO;
CREATE
    TABLE FC_LOAD_AUDIT_BATCH_RECORD_INFO
    (
        INFO_ID CHAR(38) NOT NULL COMMENT '流水号',
        BUSINESS_ID CHAR(64) NOT NULL COMMENT '平台编码',
        INFO_NAME VARCHAR(100) NOT NULL COMMENT '名称',
        RECORD_STATUS INT NOT NULL COMMENT '状态(0:未完成,1:已完成,2:失败)',
        UPDATE_TIME DATETIME NOT NULL COMMENT '更新时间',
        CREATE_TIME DATETIME NOT NULL COMMENT '建立时间',
        POST_TEXT text COMMENT '发送内容',
        PRIMARY KEY (INFO_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;


drop table if exists   FC_LOAD_AUDIT_RECORD;
CREATE
    TABLE FC_LOAD_AUDIT_RECORD
    (
        PREPAID_ACCOUNT_CHANGE_INFO_ID CHAR(38) NOT NULL COMMENT '流水号',
        BUSINESS_ID CHAR(64) COMMENT '平台编码',
        ACCOUNT_CHANGE_ID VARCHAR(60) NOT NULL COMMENT '充值账变流水号',
        ACCOUNT_CHANGE_TIME DATETIME NOT NULL COMMENT '账变时间',
        ACCOUNT_CHANGE_TYPE VARCHAR(100) NOT NULL COMMENT '账变类型',
        ACCOUNT_CHANGE_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '账变金额',
        AVAILABLE_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '可用余额',
        IP_ADDRESS CHAR(30) NOT NULL COMMENT '网络地址',
        ACCOUNT_NO_REMARK VARCHAR(512) COMMENT '卡号备注',
        LOAD_TYPE INT NOT NULL COMMENT '上分类型(0 自动上分 1 手动上分)',
        REMARK VARCHAR(512) COMMENT '备注',
        ORDER_ID VARCHAR(64) COMMENT '第三方订单号',
        CHANNEL_TYPE INT COMMENT '渠道 (1.银行2.第三方)',
        CHANNEL_NAME VARCHAR(32) COMMENT '渠道名称(NP新生IPS环迅 SF顺峰,ICBC,ABC..)',
        USER_NAME VARCHAR(32) COMMENT '用户名',
        AGENT VARCHAR(32) COMMENT '所属总代',
        LOAD_STATUS INT COMMENT '充值验证状态',
        CREATE_TIME DATETIME COMMENT '建立时间',
        LAST_UPDATE_TIME DATETIME NOT NULL COMMENT '最後更新时间',
        OPR_COMMENT VARCHAR(255) COMMENT '操作原因',
        OPERATOR VARCHAR(32) COMMENT '操作者',
        PRIMARY KEY (PREPAID_ACCOUNT_CHANGE_INFO_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;


drop table if exists   FC_LOAD_BANK_CHARGE;
CREATE
    TABLE FC_LOAD_BANK_CHARGE
    (
        BANK_CHARGE_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '银行充值手续费表ID',
        ACCOUNT_BANK_ALIAS VARCHAR(10) COLLATE utf8_bin COMMENT '银行别名',
        ACCOUNT_BANK_NAME VARCHAR(200) COLLATE utf8_bin COMMENT '开户行名',
        SAME_OTHER_CITY INT COMMENT '1同城  2异地',
        SAME_OTHER_BANK INT COMMENT '1同行  2跨行',
        AMOUNT_MIN DECIMAL(16,4) COMMENT '转账金额区间起',
        AMOUNT_MAX DECIMAL(16,4) COMMENT '转账金额区间迄',
        CHARGE DECIMAL(16,4) COMMENT '手续费',
        CHARGE_TYPE INT COMMENT '1手续费值，2手续费比率',
        PRIMARY KEY (BANK_CHARGE_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;


drop table if exists  FC_LOAD_BANK_TRANS_RETURN;
CREATE
    TABLE FC_LOAD_BANK_TRANS_RETURN
    (
        ORDER_NO CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '流水号',
        ACCOUNT_ALIAS VARCHAR(30) COLLATE utf8_bin NOT NULL COMMENT '帐户卡别名',
        CREAT_TIME DATETIME NOT NULL COMMENT '创建时间',
        AMOUNT DECIMAL(16,4) NOT NULL COMMENT '转出金额',
        STATUS INT(1) NOT NULL COMMENT '转出状态(1.转帐中, 0.转帐成功, 9.转帐失败)',
        UPDATE_TIME DATETIME COMMENT '小助手修改状态时间',
        USER_ID CHAR(38) COLLATE utf8_bin COMMENT '操作人员',
        PRIMARY KEY (ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='转出状态表';


drop table if exists  FC_LOAD_PAY_RECORD;
CREATE
    TABLE FC_LOAD_PAY_RECORD
    (
        RECORD_ID VARCHAR(64) NOT NULL COMMENT '纪录流水号',
        STATE_CODE VARCHAR(2) COMMENT '订单状态（ 0.未交易1. 处理中 2. 已交易3.交易失败)',
        SUBMIT_TIME DATETIME COMMENT '交易时间',
        COMPLATE_TIME DATETIME COMMENT '完成时间',
        COMMIT VARCHAR(255) COMMENT '备注',
        LAST_UPDATE_TIME DATETIME NOT NULL COMMENT '最后修改时间',
        TYPE CHAR(2) COMMENT '交易类型（ 1.支付2.退款）',
        REFUND_ID VARCHAR(38) COMMENT '退款编号',
        ORDER_ID VARCHAR(38) COMMENT '订单编号',
        TRADE_CHANNEL VARCHAR(32) COMMENT '交易平台类型（新生支付，支付宝...... ）',
        PLATFORM_ID VARCHAR(32) COMMENT '客戶平台',
        ORG_CODE VARCHAR(20) COMMENT '机构代码',
        REFUND_STATE_CODE VARCHAR(50) COMMENT '退款代码',
        REFUND_RECORD_NO VARCHAR(64) COMMENT '退款流水号',
        PAID_AMOUNT VARCHAR(8) COMMENT '支付金额',
        REFUND_AMOUNT VARCHAR(8) COMMENT '退款金额',
        CODE VARCHAR(100) COMMENT '代码',
        CODE_MSG VARCHAR(300) COMMENT '代码说明',
        LOAD_STATUS INT COMMENT '充值验证状态',
        OPR_COMMENT VARCHAR(255) COMMENT '操作原因',
        OPERATOR VARCHAR(32) COMMENT '操作者',
        PRIMARY KEY (RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;



 drop table if exists  FC_PAY_FROM_IPS;
CREATE
    TABLE FC_PAY_FROM_IPS
    (
        FC_ORDER_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '給新生的ID',
        MER_CODE VARCHAR(6) COLLATE utf8_bin COMMENT '商户编号',
        CURRENCY_TYPE VARCHAR(3) COLLATE utf8_bin COMMENT '币种',
        AMOUNT VARCHAR(10) COLLATE utf8_bin COMMENT '订单金额',
        SUBMIT_DATE VARCHAR(8) COLLATE utf8_bin COMMENT '订单日期',
        SUCC CHAR(1) COLLATE utf8_bin COMMENT '成功标志',
        MSG VARCHAR(255) COLLATE utf8_bin COMMENT '发卡行的返回信息',
        ATTACH VARCHAR(1024) COLLATE utf8_bin COMMENT '商户数据包',
        IPS_BILL_NO VARCHAR(18) COLLATE utf8_bin COMMENT 'IPS 订 单 号',
        RET_ENCODE_TYPE CHAR(2) COLLATE utf8_bin COMMENT '交易返回签名方式',
        SIGNATURE VARCHAR(1024) COLLATE utf8_bin COMMENT '数字签名信息',
        BANK_BILL_NO VARCHAR(30) COLLATE utf8_bin COMMENT '银行订单号',
        PRIMARY KEY (FC_ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;



drop table if exists FC_PAY_FROM_SF;
CREATE
    TABLE FC_PAY_FROM_SF
    (
        FC_ORDER_NO VARCHAR(32) NOT NULL COMMENT '給新生的ID',
        PAY_ORDER_NO VARCHAR(50) COMMENT '系统订单号',
        MER_CHANT_ID VARCHAR(12) COMMENT '商户ID',
        MER_ORDER_NO VARCHAR(32) COMMENT '商户订单号',
        CARD_NO VARCHAR(12),
        CARD_TYPE VARCHAR(4),
        FACT_MONEY VARCHAR(10),
        PAY_RESULT VARCHAR(10),
        CUSTOMIZE_A VARCHAR(255),
        CUSTOMIZE_B VARCHAR(255),
        CUSTOMIZE_C VARCHAR(255),
        PAY_TIME VARCHAR(30),
        ERROR_MSG VARCHAR(255),
        SIGN VARCHAR(100),
        PRIMARY KEY (FC_ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;


 drop table if exists FC_PAY_ORDER_RECORD;
CREATE
    TABLE FC_PAY_ORDER_RECORD
    (
        FC_RECORD_ID VARCHAR(64) NOT NULL COMMENT '纪录流水号',
        FC_MESSAGE_NO CHAR(64) NOT NULL COMMENT '发送命令号',
        ORDER_NO VARCHAR(38) NOT NULL COMMENT '客户订单编号',
        STATE_CODE VARCHAR(2) COMMENT '订单状态（ 0.未交易1. 处理中 2. 已交易3.交易失败)',
        SUBMIT_TIME DATETIME NOT NULL COMMENT '交易时间',
        COMPLATE_TIME DATETIME COMMENT '完成时间',
        COMMIT VARCHAR(255) COMMENT '备注',
        LAST_UPDATE_TIME DATETIME NOT NULL COMMENT '最后修改时间',
        TYPE CHAR(2) COMMENT '交易类型（ 1.支付2.退款）',
        REFUND_ID VARCHAR(38) COMMENT '退款编号',
        ORDER_ID VARCHAR(38) COMMENT '订单编号',
        TRADE_CHANNEL VARCHAR(32) COMMENT '交易平台类型（新生支付，支付宝...... ）',
        PLATFORM_ID VARCHAR(32) COMMENT '客戶平台',
        ORG_CODE VARCHAR(20) COLLATE utf8_bin COMMENT '机构代码',
        REFUND_STATE_CODE VARCHAR(50) COLLATE utf8_bin COMMENT '退款代码',
        REFUND_RECORD_NO VARCHAR(64) COLLATE utf8_bin COMMENT '退款流水号',
        PAID_AMOUNT VARCHAR(8) COLLATE utf8_bin COMMENT '支付金额',
        REFUND_AMOUNT VARCHAR(8) COLLATE utf8_bin COMMENT '退款金额',
        CODE VARCHAR(100) COLLATE utf8_bin COMMENT '代码',
        CODE_MSG VARCHAR(300) COLLATE utf8_bin COMMENT '代码说明',
        PRIMARY KEY (FC_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;


 drop table if exists FC_PAY_TO_IPS;
CREATE
    TABLE FC_PAY_TO_IPS
    (
        FC_MESSAGE_NO CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '发送命令号',
        SUBMIT_DATE VARCHAR(8) COLLATE utf8_bin COMMENT '订单日期',
        CURRENCY_TYPE VARCHAR(3) COLLATE utf8_bin COMMENT '币种',
        GATEWAY_TYPE VARCHAR(2) COLLATE utf8_bin COMMENT '支付卡种',
        LANG VARCHAR(10) COLLATE utf8_bin COMMENT '语言',
        MERCHANT_URL VARCHAR(255) COLLATE utf8_bin COMMENT '支付结果成功返回的商户URL',
        FAIL_URL VARCHAR(255) COLLATE utf8_bin COMMENT '支付结果失败返回的商户URL',
        RET_ENCODE_TYPE VARCHAR(2) COLLATE utf8_bin COMMENT '交易返回接口加密方式',
        RET_TYPE CHAR(1) COLLATE utf8_bin COMMENT '返回方式',
        DO_CREDIT CHAR(1) COLLATE utf8_bin COMMENT '直连选项',
        BANK_CO VARCHAR(5) COLLATE utf8_bin COMMENT '银行代码',
        PRIMARY KEY (FC_MESSAGE_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;


 drop table if exists FC_PAY_TO_SF;
CREATE
    TABLE FC_PAY_TO_SF
    (
        FC_MESSAGE_NO CHAR(38) NOT NULL COMMENT '发送命令号',
        CARD_TYPE VARCHAR(4) COMMENT '商品代码,15=网银, 16=盛付通卡',
        BANK_ID VARCHAR(12) COMMENT '银行代码',
        CUSTOMIZE_A VARCHAR(255) COMMENT '自定义A, 通知时原样返回',
        CUSTOMIZE_B VARCHAR(255) COMMENT '自定义B, 通知时原样返回',
        CUSTOMIZE_C VARCHAR(255) COMMENT '自定义C, 通知时原样返回',
        PRIMARY KEY (FC_MESSAGE_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;


drop table if exists   FC_RISK_ABNORMAL_ACCOUNT;
CREATE
    TABLE FC_RISK_ABNORMAL_ACCOUNT
    (
        ABNORMAL_ID CHAR(50) COLLATE utf8_bin NOT NULL COMMENT '异常ID',
        BUSINESS_ID CHAR(50) COLLATE utf8_bin COMMENT '所属平台',
        ABNORMAL_TYPE CHAR(2) COLLATE utf8_bin COMMENT '异常类型（01：会员账号，02：IP，03：银行卡）',
        ABNORMAL_VALUE VARCHAR(50) COLLATE utf8_bin COMMENT '异常值',
        STATUS CHAR(2) COLLATE utf8_bin COMMENT '启用状态（01：启用，02：不启用）',
        VIEW_COLOR VARCHAR(50) COLLATE utf8_bin COMMENT '高亮显示颜色（01：红，02：黄，03：紫）',
        CREATE_TIME DATETIME COMMENT '创建时间',
        UPDATE_TIME DATETIME COMMENT '修改时间',
        CREATE_USERID VARCHAR(50) COLLATE utf8_bin COMMENT '创建人',
        COMMENTS VARCHAR(500) COLLATE utf8_bin COMMENT '备注',
        PRIMARY KEY (ABNORMAL_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='异常账号管理表';


drop table if exists FC_RISK_USER_REMARK;
CREATE
    TABLE FC_RISK_USER_REMARK
    (
        CUSTOMER_ACCOUNT_INFO_ID CHAR(38) NOT NULL COMMENT '备注ID',
        BUSINESS_ID CHAR(64) NOT NULL COMMENT '平台编码',
        USER_NAME VARCHAR(32) COMMENT '会员名',
        REMARK VARCHAR(500) COMMENT '备注内容',
        RECORD_DATA DATETIME COMMENT '备注时间',
        OPERATOR VARCHAR(32) COMMENT '备注操作员',
        PRIMARY KEY (CUSTOMER_ACCOUNT_INFO_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='风控会员备注';



drop table if exists FC_WITHDRAW_REQMONEY_RECORD;
CREATE
    TABLE FC_WITHDRAW_REQMONEY_RECORD
    (
        REQ_ID VARCHAR(38) COLLATE utf8_bin NOT NULL COMMENT '请款ID',
        ACCOUNT_ALIAS VARCHAR(38) COLLATE utf8_bin COMMENT '卡别名',
        REQ_AMOUNT DECIMAL(16,4) COMMENT '请款金额',
        REQ_TIME DATETIME COMMENT '请款时间',
        PROCESS_ID CHAR(64) COLLATE utf8_bin,
        RESERVED1 VARCHAR(64) COLLATE utf8_bin COMMENT '预留一',
        RESERVED2 VARCHAR(64) COLLATE utf8_bin COMMENT '预二',
        PRIMARY KEY (REQ_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;



alter table FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO add column LOAD_STATUS INT;
alter table FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO add column ORDER_ID VARCHAR(64);
alter table FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO add column CHANNEL_TYPE INT;
alter table FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO add column CHANNEL_NAME VARCHAR(32);
alter table FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO add column USER_NAME VARCHAR(32);
alter table FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO add column AGENT VARCHAR(32);

alter table FC_LOAD_CUSTOMER_EXCEPTION_RECORD add column CREATOR CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '操作员';
alter table FC_LOAD_CUSTOMER_EXCEPTION_RECORD modify column REAL_NAME VARCHAR(32) COLLATE utf8_bin COMMENT '会员真实姓名';
alter table FC_LOAD_CUSTOMER_EXCEPTION_RECORD modify column BANK_SERIAL_NO VARCHAR(50) COLLATE utf8_bin COMMENT '银行流水号';
alter table FC_LOAD_CUSTOMER_EXCEPTION_RECORD modify column RAW_COMMENT VARCHAR(32) COLLATE utf8_bin COMMENT '原附言';





        