use fcpay;
DROP TABLE IF EXISTS
    FC_BANK_DETAIL_QUERY;
CREATE
    TABLE FC_BANK_DETAIL_QUERY
    (
        ORDER_NO CHAR(38) COLLATE utf8_bin NOT NULL COMMENT 'ORDER_NO',
        CARD_NO VARCHAR(30) COLLATE utf8_bin NOT NULL COMMENT '卡号别名',
        FILE_PATH VARCHAR(256) COLLATE utf8_bin COMMENT '文件路径',
        CREATED_TIME DATETIME NOT NULL COMMENT '下载时间',
        START_TIME DATETIME COMMENT '下载开始时间',
        END_TIME DATETIME COMMENT '下载结束时间',
        DOWNLOAD_TIME DATETIME COMMENT '下载完成时间',
        CMD_TYPE VARCHAR(2) COLLATE utf8_bin NOT NULL COMMENT '命令类型',
        STATUS INT NOT NULL COMMENT '默认为1',
        USER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
        PRIMARY KEY (ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_BANKMSG_ACCOUNT_QUERY_RESULT;
CREATE
    TABLE FC_BANKMSG_ACCOUNT_QUERY_RESULT
    (
        RES_ORDERNO VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '交易序列号',
        RES_CARDALIAS CHAR(38) COLLATE utf8_bin COMMENT '账户编号',
        RES_BANKNAME VARCHAR(64) COLLATE utf8_bin COMMENT '银行名称',
        RES_CREATE_TIME DATETIME COMMENT '交易入库时间',
        RES_TRADE_DATE DATE COMMENT '卡交易日期',
        RES_TRADE_TIME TIME COMMENT '卡交易时间',
        RES_TRANFLAG INT COMMENT '卡收付标志：余额查询时,0-有效,1-无效            
自动余额查询.0- 收款,1-付款',
        RES_SRC_CARDNO VARCHAR(32) COLLATE utf8_bin COMMENT '付款账号',
        RES_SRC_CARDNAME VARCHAR(512) COLLATE utf8_bin COMMENT '付款人用户名称',
        RES_MONEY DECIMAL(16,4) COMMENT '付款金额',
        RES_POUNDAGE DECIMAL(16,4) COMMENT '手续费',
        RES_SRC_BANKNAME VARCHAR(32) COLLATE utf8_bin COMMENT '付款人银行类型',
        RES_SRC_BANKBRANCENAME VARCHAR(512) COLLATE utf8_bin COMMENT '开户行名称',
        RES_SRC_BANKBRANCHNO VARCHAR(32) COLLATE utf8_bin COMMENT '开户行号',
        RES_BALANCE DECIMAL(16,4) COMMENT '卡账户余额',
        RES_AVAIABLE DECIMAL(16,4) COMMENT '卡可用余额',
        RES_TRANSACTION_WAY VARCHAR(64) COLLATE utf8_bin COMMENT '交易渠道',
        RES_TRANSACTION_STATE VARCHAR(32) COLLATE utf8_bin,
        RES_TRANSACTION_COMMENTS VARCHAR(512) COLLATE utf8_bin COMMENT '交易附言',
        RES_DEST_CARDNO VARCHAR(32) COLLATE utf8_bin COMMENT '收款账号',
        RES_DEST_CARDNAME VARCHAR(512) COLLATE utf8_bin COMMENT '收款人用户名',
        RES_DEST_BANKNAME VARCHAR(64) COLLATE utf8_bin COMMENT '收款人银行类型',
        RES_DEST_BANK_BRANCHNAME VARCHAR(512) COLLATE utf8_bin COMMENT '收款方开户行名称',
        RES_DEST_BANKBRANCH_NO VARCHAR(64) COLLATE utf8_bin COMMENT '收款方开户行号',
        RES_QUERY_TYPE INT COMMENT '交易类型：1-自动查询,2余额查询',
        RES_STATE_MESSAGE VARCHAR(512) COLLATE utf8_bin COMMENT '转账结果信息',
        AUDIT_FLAG INT,
        PRIMARY KEY (RES_ORDERNO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='自动查询、余额查询结果表';
DROP TABLE IF EXISTS
    FC_BANKMSG_ACCOUNT_SERVICE_REF;
CREATE
    TABLE FC_BANKMSG_ACCOUNT_SERVICE_REF
    (
        ACCOUNT_ALIAS CHAR(38) NOT NULL COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        ACCOUNT_NAME VARCHAR(64) COMMENT '持卡人',
        SERVICE_NO VARCHAR(20) COMMENT '服务器编号',
        UK_NO VARCHAR(20) COMMENT 'U口编号',
        OS_IP CHAR(38) COMMENT '操作系统IP',
        STATUS INT COMMENT '状态1-已启动,2-已登入.3-已登出;4-未启动;5-卡异常(如检测不到心跳造成的)',
        ACCOUNT_BALANCE DECIMAL(16,4) COMMENT '账户余额',
        ACCOUNT_BANK_ALIAS CHAR(38) COMMENT '余额',
        STATUS_UPD_TIME DATETIME COMMENT '状态修改时间',
        PRIMARY KEY (ACCOUNT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='卡状态监控表';
DROP TABLE IF EXISTS
    FC_BANKMSG_ASSISTANT_TO_WEB;
CREATE
    TABLE FC_BANKMSG_ASSISTANT_TO_WEB
    (
        MSG_ORDERID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '交易序列号',
        MSG_CONTENT VARCHAR(1000) COLLATE utf8_bin NOT NULL COMMENT '消息内容',
        MSG_CMDTYPE INT COMMENT '消息类型:8-余额查询结果.10-转账结果,14-网银助手返回登录结果,16-网银助手返回注销结果',
        MSG_CREATE_TIME DATETIME NOT NULL COMMENT '入库时间',
        MSG_STATUS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '消息状态:0-未拆解,1-已拆解',
        MSG_UPDATE_TIME DATETIME NOT NULL COMMENT '消息状态修改时间',
        MSG_RESERV1 VARCHAR(256) COLLATE utf8_bin COMMENT '保留字段1',
        MSG_RESERV2 VARCHAR(2000) COLLATE utf8_bin COMMENT '保留字段2',
        PRIMARY KEY (MSG_ORDERID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='网银助手发往充提系统的报文';
DROP TABLE IF EXISTS
    FC_BANKMSG_ASSISTANT_TO_WEB_HB;
CREATE
    TABLE FC_BANKMSG_ASSISTANT_TO_WEB_HB
    (
        CARD_IDENTIFY CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '卡别名',
        CARD_BANK VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '卡所属银行简称',
        CARD_UPDATE_TIME DATETIME NOT NULL COMMENT '心跳接收时间',
        CARD_LOOP_TIME VARCHAR(8) COLLATE utf8_bin NOT NULL COMMENT '心跳间隔,秒单位',
        CARD_STATUS VARCHAR(8) COLLATE utf8_bin NOT NULL COMMENT '卡状态:0-正常,1-不正常',
        CARD_RESERVED1 VARCHAR(512) COLLATE utf8_bin COMMENT '备注1',
        CARD_RESERVED2 VARCHAR(512) COLLATE utf8_bin COMMENT '备注2',
        PRIMARY KEY (CARD_IDENTIFY)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='卡状态监控心跳表, 当卡心跳异常时, 修改卡命令状态表,修改卡账户状态';
DROP TABLE IF EXISTS
    FC_BANKMSG_CARD_STATUS_INFO;
CREATE
    TABLE FC_BANKMSG_CARD_STATUS_INFO
    (
        MSG_ID INT NOT NULL COMMENT '卡状态命令信息ID',
        MSG_CARDNO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '卡别号',
        MSG_BANKNAME VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '卡所属银行名称',
        MSG_CREATE_TIME DATETIME NOT NULL COMMENT '交易入库时间',
        MSG_STATUS INT NOT NULL COMMENT '交易状态:0-失败.1-成功(注册或注销或卡登入或者卡登出)',
        MSG_CMDTYPE INT COMMENT '交易命令类型:1-注册(启动),4-注销(未启动),13-卡登入,15-卡登出',
        MSG_UPD_ACCOUNT INT COMMENT ' 是否已修改FC_ACCOUNT_SERVICE_REF表的status字段,             
0-否,1-是,修改成功,2-修改失败.',
        MSG_ERROR_INFO VARCHAR(128) COLLATE utf8_bin COMMENT '状态处理失败原因',
        PRIMARY KEY (MSG_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='登录，登出，注册，注销';
DROP TABLE IF EXISTS
    FC_BANKMSG_CTRL;
CREATE
    TABLE FC_BANKMSG_CTRL
    (
        KEYY VARCHAR(64) COLLATE utf8_bin NOT NULL,
        VALUEE VARCHAR(128) COLLATE utf8_bin,
        DESCS VARCHAR(512) COLLATE utf8_bin,
        PRIMARY KEY (KEYY)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_BANKMSG_TRANS_RESULT_INFO;
CREATE
    TABLE FC_BANKMSG_TRANS_RESULT_INFO
    (
        TRAN_ORDERNO VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '交易序列号',
        TRAN_CARD_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户编号',
        TRAN_BANK_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '银行名称',
        TRAN_CREATE_TIME DATETIME NOT NULL COMMENT '交易入库时间',
        TRAN_SRC_CARDNO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '付款账户',
        TRAN_SRC_CARDNAME VARCHAR(512) COLLATE utf8_bin NOT NULL COMMENT '付款人用户名称',
        TRAN_DEST_CARDNO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '收款账户',
        TRAN_DEST_CARDNAME VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '收款人姓名',
        TRAN_MONEY DECIMAL(16,4) NOT NULL COMMENT '转账金额',
        TRAN_POUNDAGE DECIMAL(16,4) NOT NULL COMMENT '转账手续费',
        TRAN_RESULT_STATE INT NOT NULL COMMENT '转账处理结果',
        TRAN_RESULT_MESSAGE VARCHAR(512) COLLATE utf8_bin NOT NULL COMMENT '转账处理结果信息',
        TRAN_RESERVE1 VARCHAR(64) COLLATE utf8_bin COMMENT '备注1',
        TRAN_RESERVE2 VARCHAR(512) COLLATE utf8_bin COMMENT '备注2',
        TRAN_TIME DATETIME COMMENT '网银助手的转账时间',
        PRIMARY KEY (TRAN_ORDERNO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='转账交易信息表';
DROP TABLE IF EXISTS
    FC_BANKMSG_WEB_TO_ASSISTANT;
CREATE
    TABLE FC_BANKMSG_WEB_TO_ASSISTANT
    (
        MSG_ORDERID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '交易序列号',
        MSG_CARD_IDENTIFY CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户编号',
        MSG_CONTENT VARCHAR(2000) COLLATE utf8_bin NOT NULL COMMENT '消息内容',
        MSG_CMDTYPE INT NOT NULL COMMENT '消息类型',
        MSG_CREATE_TIME DATETIME NOT NULL COMMENT '消息入库时间',
        MSG_STATUS INT NOT NULL COMMENT '消息状态:0-消息入库,1-发往MQ,2-网银助手接收成功',
        MSG_UPDATE_TIME DATETIME COMMENT '消息状态修改时间',
        MSG_RESERVED1 VARCHAR(255) COLLATE utf8_bin COMMENT '保留字段1',
        MSG_RESERVED2 VARCHAR(1024) COLLATE utf8_bin COMMENT '保留字段2',
        PRIMARY KEY (MSG_ORDERID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='充提系统发给网银助手的交易.(自动登入登入,余额查询交易,卡转账交易)';
DROP TABLE IF EXISTS
    FC_CRM_CUSTOMER;
CREATE
    TABLE FC_CRM_CUSTOMER
    (
        FC_CUSTOMER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '客户ID',
        CUSTOMER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '会员名',
        CUSTOMER_REAL_NAME VARCHAR(32) COLLATE utf8_bin COMMENT '姓名',
        MOBILE VARCHAR(20) COLLATE utf8_bin COMMENT '联系方式',
        AGENT VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '代理人',
        BIRTHDAY DATE COMMENT '生日',
        STATUS INT NOT NULL COMMENT '有效状态',
        PRIMARY KEY (FC_CUSTOMER_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户关联信息表';
DROP TABLE IF EXISTS
    FC_CRM_CUSTOMER_ACCOUNT;
CREATE
    TABLE FC_CRM_CUSTOMER_ACCOUNT
    (
        ACCOUNT_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户ID',
        FC_CUSTOMER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '客户ID',
        ACCOUNT_NO VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '银行账户号',
        ACCOUNT_NAME VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '银行账户名',
        ACCOUNT_BANK_NAME VARCHAR(200) COLLATE utf8_bin NOT NULL COMMENT '银行开户行名(内部转账如果不走加急转账，可以走普通转账，节省费用)',
        BANK_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '银行别名(充提平台的简码，要与游戏系统有对应关系)',
        ACCOUNT_STATUS INT NOT NULL COMMENT '账户状态(1正常，2停用，3冻结，4预警或危险，5已注销)',
        ACCOUNT_STATUS_INFO VARCHAR(50) COLLATE utf8_bin COMMENT '账户状态说明(如果改变了状态，可以增加说明描述，以备跟踪原因)',
        ACCOUNT_EDIT_DATETIME DATETIME COMMENT '账户变更状态时间',
        ACCOUNT_REGISTER_DATETIME DATETIME NOT NULL COMMENT '账户注册时间',
        IS_DEFAULT INT(1) NOT NULL COMMENT '是否默认账户',
        PRIMARY KEY (ACCOUNT_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户账户表(会员卡账户信息,前期逐步积累客户的账户信息)';
DROP TABLE IF EXISTS
    FC_CRM_CUSTOMER_BLACKLIST_INFO;
CREATE
    TABLE FC_CRM_CUSTOMER_BLACKLIST_INFO
    (
        FC_CUSTOMER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '客户ID',
        LEVEL INT NOT NULL COMMENT '级别(-1黑名单，0 正常，1白名单)',
        VALID_BEND_TIME2 DATETIME COMMENT '有效结束时间',
        VALID_BEGIN_TIME DATETIME COMMENT '有效开始时间',
        VALID_FLAG TINYINT(1) NOT NULL COMMENT '有效状态',
        PRIMARY KEY (FC_CUSTOMER_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户黑名单表';
DROP TABLE IF EXISTS
    FC_CRM_CUSTOMER_PAY_ACCOUNT;
CREATE
    TABLE FC_CRM_CUSTOMER_PAY_ACCOUNT
    (
        FC_CUSTOMER_PAY_ACCOUNT_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '钱包账户ID',
        FC_CUSTOMER_ID CHAR(38) COLLATE utf8_bin COMMENT '客户ID',
        PAY_ACCOUNT_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '平台钱包账户号',
        BALANCE DECIMAL(16,4) NOT NULL COMMENT '平台钱包余额',
        AVAILABLE_BALANCE DECIMAL(16,4) NOT NULL COMMENT '可用余额',
        FROZEN_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '冻结金额',
        VALID_BEGIN_TIME DATETIME COMMENT '起始有效时间',
        VALID_END_TIME DATETIME COMMENT '起始结束时间',
        VALID_STATE TINYINT(1) NOT NULL COMMENT '有效状态',
        PRIMARY KEY (FC_CUSTOMER_PAY_ACCOUNT_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='平台钱包账户信息表(客户在支付平台注册的账户)';
DROP TABLE IF EXISTS
    FC_CRM_MEMBER;
CREATE
    TABLE FC_CRM_MEMBER
    (
        FC_CUSTOMER_TRADE_ID VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '会员ID',
        BUSINESS_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '平台编码',
        FC_CUSTOMER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '客户ID',
        CUSTOMER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '会员名，来源于游戏平台会员名',
        CUSTOMER_REAL_NAME VARCHAR(32) COLLATE utf8_bin COMMENT '姓名',
        MOBILE VARCHAR(20) COLLATE utf8_bin COMMENT '联系方式',
        AGENT VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '代理人',
        BIRTHDAY DATE COMMENT '生日',
        STATUS INT NOT NULL COMMENT '有效状态',
        REGISTE_TIME DATETIME,
        PRIMARY KEY (FC_CUSTOMER_TRADE_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='会员信息表';
DROP TABLE IF EXISTS
    FC_IMAGE;
CREATE
    TABLE FC_IMAGE
    (
        ID INT NOT NULL AUTO_INCREMENT,
        CARD_NO VARCHAR(30) COLLATE utf8_bin NOT NULL,
        IMG_SRC VARCHAR(200) COLLATE utf8_bin NOT NULL,
        IMG_CODE VARCHAR(20) COLLATE utf8_bin,
        CREATE_TIME DATETIME NOT NULL,
        CMD_TYPE VARCHAR(2) COLLATE utf8_bin NOT NULL,
        ORDER_NO VARCHAR(30) COLLATE utf8_bin NOT NULL,
        PRIMARY KEY (ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_IMAGE_VARIFY;
CREATE
    TABLE FC_IMAGE_VARIFY
    (
        ID VARCHAR(38) COLLATE utf8_bin NOT NULL,
        CARD_NO VARCHAR(30) COLLATE utf8_bin COMMENT '银行卡号',
        IMG_PATH VARCHAR(200) COLLATE utf8_bin,
        IMG_CODE VARCHAR(20) COLLATE utf8_bin,
        CREATED_TIME DATETIME NOT NULL,
        CMD_TYPE VARCHAR(2) COLLATE utf8_bin NOT NULL,
        ORDER_NO VARCHAR(30) COLLATE utf8_bin NOT NULL,
        ENTERED_TIME DATETIME,
        STATUS INT COMMENT '0未录入 1已录入',
        IMG_URL VARCHAR(300) COLLATE utf8_bin,
        PRIMARY KEY (ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_IMAGE_YEKETAVIRP;
CREATE
    TABLE FC_IMAGE_YEKETAVIRP
    (
        ID CHAR(38) NOT NULL,
        IMAGE_NAME VARCHAR(100) NOT NULL,
        IMAGE_PATH VARCHAR(200) NOT NULL,
        YEKETAVIRP VARCHAR(100) NOT NULL,
        IMAGE_STATUS INT DEFAULT '1' NOT NULL,
        CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
        IMG_URL VARCHAR(300),
        PRIMARY KEY (ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_INNERC_ACCOUNT;
CREATE
    TABLE FC_INNERC_ACCOUNT
    (
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        ACCOUNT_NO VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '账户号',
        ACCOUNT_NAME VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '账户名称',
        ACCOUNT_BANK_NAME VARCHAR(200) COLLATE utf8_bin NOT NULL COMMENT '开户行名(内部转账如果不走加急转账，可以走普通转账，节省费用)',
        ACCOUNT_BANK_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '银行别名(有字典表)',
        ACCOUNT_GROUP_ID VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '账户组ID',
        ACCOUNT_AUTO_TYPE INT NOT NULL COMMENT '账户处理方式(1.自动，0手动，用于出款卡的控制)',
        ACCOUNT_STATUS INT NOT NULL COMMENT '账户状态(1正常，2停用，3冻结，4预警或危险，5已注销)',
        ACCOUNT_STATUS_INFO VARCHAR(200) COLLATE utf8_bin COMMENT '账户状态说明(如果改变了状态，可以增加说明描述，以备跟踪原因)',
        PAYMENT_TYPE INT NOT NULL COMMENT '充提标识(1为收入类账户（收款卡），2为支出类账户（付款卡），0即可收入也可支出，系统暂时无此类账户)',
        ACCOUNT_TIER INT NOT NULL COMMENT '账户层级(0,充提账户，1中转账户，2资金池账户（资金池账户内部由其它表来具体描述）)',
        UPDATE_TIME DATETIME COMMENT '账户变更状态时间',
        CREATE_TIME DATETIME NOT NULL COMMENT '账户注册时间',
        CREATED_BY VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '注册人',
        MODIFIED_BY VARCHAR(32) COLLATE utf8_bin COMMENT '修改人',
        BANK_NAME VARCHAR(30) COLLATE utf8_bin NOT NULL COMMENT '银行全称',
        EMAIL VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '转账EMAIL',
        BUSINESS_ID CHAR(38) COLLATE utf8_bin,
        INTERVAL_SECONDS INT DEFAULT '30' NOT NULL,
		ALARM_VALUE varchar(32),
        PRIMARY KEY (ACCOUNT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='卡账户表(只管理内部卡账户，不管理第三方账户)';
DROP TABLE IF EXISTS
    FC_INNERC_ACCOUNT_DETAIL;
CREATE
    TABLE FC_INNERC_ACCOUNT_DETAIL
    (
        ACCOUNT_DETAIL_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '内部账户明细账ID',
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        AMOUNT DECIMAL(16,4) COMMENT '交易金额',
        TRANS_TIME DATETIME COMMENT '交易时间',
        TRANS_FLAG INT COMMENT '收付标志(1,收入，2支出)',
        CURRENCY INT COMMENT '币种(默认1，人民币)',
        ACCOUNT_TYPE INT COMMENT '账务类型(1系统记账（平台记得都是系统账），1.手工记账（手工调账，人工打款，平台没记录的账务变动）)',
        CURRENT_RELATIONSHIPS INT COMMENT '往来关系(1.内部测试（1元测试），2.与内部账户往来，3.与外部账户往来)',
        FUND_USED INT COMMENT '资金用途(1.往来收付，2.手续费)',
        TRANS_COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '交易附言',
        BANK_TRANS_COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '银行交易摘要',
        BANK_FLOW VARCHAR(32) COLLATE utf8_bin COMMENT '银行交易流水号',
        POUNDAGE DECIMAL(16,4) NOT NULL COMMENT '手续费',
        LAST_BALANCE DECIMAL(16,4) COMMENT '账户当前余额',
        FC_ORDER_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '平台交易流水号(充提平台的转账操作视为与银行发起的一次交易，每次会生成一个流水号，此流水号为交易的唯一标识，也是发给网银助手的命令序列号)',
        FC_TRADE_CODE INT COMMENT '业务表标识(标识不同的业务表，产生交易的业务表，与平台交易流水号共同使用（放款表 出款表 回转表 充值表 ）)',
        TO_ACCOUNT_ID VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '交易对手账户ID',
        TO_ACCOUNT_TYPE INT NOT NULL COMMENT '交易对手类型(1，内部账户，2，客户账户)',
        PRIMARY KEY (ACCOUNT_DETAIL_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='内部账户明细账表(记录各账户的明细账，有手续费的，会形成两笔记录，所有交易都会影响此表，充值，提现，转回，人工处理网银（';
DROP TABLE IF EXISTS
    FC_INNERC_ACCOUNT_GROUP;
CREATE
    TABLE FC_INNERC_ACCOUNT_GROUP
    (
        ACCOUNT_GROUP_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户组ID',
        BUSINESS_ID CHAR(38) COLLATE utf8_bin COMMENT '平台编码',
        ACCOUNT_GROUP_NAME VARCHAR(30) COLLATE utf8_bin COMMENT '账户组名称',
        ACCOUNT_GROUP_DESC VARCHAR(100) COLLATE utf8_bin COMMENT '账户组描述',
        PARENT_ACCOUNT_GROUP_ID CHAR(38) COLLATE utf8_bin COMMENT '父账户组ID',
        BEGIN_TIME DATETIME COMMENT '有效开始时间',
        END_TIME DATETIME COMMENT '有效结束时间',
        ACCOUNT_TIER INT,
        PRIMARY KEY (ACCOUNT_GROUP_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='账户组表(每个账户组属于不同的账户类型，同时也属于不同的业务平台)';
DROP TABLE IF EXISTS
    FC_INNERC_ACCOUNT_LEDGER;
CREATE
    TABLE FC_INNERC_ACCOUNT_LEDGER
    (
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        LAST_BALANCE DECIMAL COMMENT '账户当前余额',
        LAST_TIME DATETIME COMMENT '最后一次变动时间',
        PRIMARY KEY (ACCOUNT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='内部账户分户账表(记录各账户的分户账)';
DROP TABLE IF EXISTS
    FC_INNERC_BANK_ACCOUNT_SECURITY;
CREATE
    TABLE FC_INNERC_BANK_ACCOUNT_SECURITY
    (
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        LOGIN_NAME VARCHAR(50) COLLATE utf8_bin COMMENT '银行登陆名称',
        LOGIN_PASSWORD VARCHAR(50) COLLATE utf8_bin COMMENT '银行登陆密码',
        TRANSACT_PASSWORD VARCHAR(50) COLLATE utf8_bin COMMENT '银行交易密码',
        UFLAG INT COMMENT '是否需要U盾(0不需要U盾可以查询，1需要U盾查询，2需要U盾转账)',
        UNO VARCHAR(100) COLLATE utf8_bin COMMENT 'U盾编号',
        UPDATE_TIME DATETIME COMMENT '修改时间',
        ENCRYPT VARCHAR(50) COLLATE utf8_bin COMMENT '加密算法(密码等需要加密，加密算法不同账号可以不同，不同阶段可以不同)',
        UD_PASSWORD VARCHAR(50) COLLATE utf8_bin COMMENT 'U盾密码',
        BANK_WEB_BROWER_DLL VARCHAR(50) COLLATE utf8_bin COMMENT '对应的动态库',
        ENCRYPT_KEY VARCHAR(100) COLLATE utf8_bin,
        PRIMARY KEY (ACCOUNT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='银行账户安全信息管理表(银行账户安全性管理)';
DROP TABLE IF EXISTS
    FC_INNERC_BANK_INFO;
CREATE
    TABLE FC_INNERC_BANK_INFO
    (
        BANK_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '银行别名',
        BANK_NAME VARCHAR(30) COLLATE utf8_bin NOT NULL COMMENT '银行全称',
        INTER_BANK_BANLANCE VARCHAR(10) COLLATE utf8_bin,
        SAME_BANK_BANLANCE VARCHAR(10) COLLATE utf8_bin,
        PRIMARY KEY (BANK_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='银行简码字典表(银行简码字典)';
DROP TABLE IF EXISTS
    FC_INNERC_MONITOR_ORDER;
CREATE
    TABLE FC_INNERC_MONITOR_ORDER
    (
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '卡别名',
        STATUS INT(1) COMMENT '完成状态0，未完成，1完成',
        CREATE_TIME DATETIME COMMENT '创建时间',
        OPERATOR VARCHAR(64) COLLATE utf8_bin COMMENT '操作员',
        PRIMARY KEY (ACCOUNT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='该表记录是监控 登陆时发送指令状态的表';
DROP TABLE IF EXISTS
    FC_INNERC_PAYMENT_ACCOUNT;
CREATE
    TABLE FC_INNERC_PAYMENT_ACCOUNT
    (
        PAYMENT_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '第三方支付账户ID',
        SELLER_NO VARCHAR(100) COLLATE utf8_bin COMMENT '商户支付账号',
        SELLER_ALIAS VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '商户账户别名(自己内部定义的别名，用于区分不同账户)',
        SELLER_NAME VARCHAR(100) COLLATE utf8_bin COMMENT '商户名称',
        SELLER_INFO VARCHAR(100) COLLATE utf8_bin COMMENT '商户描述',
        PAYMENT_ALIAS VARCHAR(10) COLLATE utf8_bin COMMENT '第三方支付别名',
        BUSINESS_ID CHAR(64) COLLATE utf8_bin COMMENT '平台编码',
        ACCOUNT_AUTO_TYPE INT COMMENT '账户处理方式(1.自动，0手动，用于出款卡的控制)',
        ACCOUNT_STATUS INT COMMENT '账户状态(1正常，2停用，3冻结，4预警或危险，5已注销)',
        ACCOUNT_STATUS_INFO VARCHAR(50) COLLATE utf8_bin COMMENT '账户状态说明(如果改变了状态，可以增加说明描述，以备跟踪原因)',
        ACCOUNT_UPDATE_TIME DATETIME COMMENT '账户变更状态时间',
        ACCOUNT_REGISTER_TIME DATETIME COMMENT '账户注册时间',
        PAYMENT_TYPE INT COMMENT '收付属性(1为收入类账户（收款卡），2为支出类账户（付款卡），0即可收入也可支出，系统暂时无此类账户)',
        ACCOUNT_TIER INT COMMENT '账户层级(0,充提账户，1中转账户，2资金池账户（资金池账户内部由其它表来具体描述）)',
        PRIMARY KEY (PAYMENT_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='第三方支付账户表(第三方账户表)';
DROP TABLE IF EXISTS
    FC_INNERC_PAYMENT_ACCOUNT_SECURITY;
CREATE
    TABLE FC_INNERC_PAYMENT_ACCOUNT_SECURITY
    (
        PAYMENT_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '第三方支付账户ID',
        LOGIN_NAME VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '第三方支付登陆名称',
        LOGIN_PASSWORD VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '第三方支付登陆密码',
        TRANSACT_PASSWORD VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '第三方支付交易密码',
        UFLAG INT NOT NULL COMMENT '是否需要U盾(0不需要U盾可以查询，1需要U盾查询，2需要U盾转账)',
        UNO VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT 'U盾编号',
        UPDATE_TIME DATETIME NOT NULL COMMENT '修改时间',
        ENCRYPT VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '加密算法(密码等需要加密，加密算法不同账号可以不同，不同阶段可以不同)',
        DEFAULT_TYPE INT COMMENT '默认类型(0为登录，支付默认名称，1为登录默认名称，2为支付默认名称)',
        PRIMARY KEY (PAYMENT_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='第三方支付账户安全信息管理表(第三方支付账户安全性管理，由于第三方支付有多个登录账户，支付账户，所以一个商户可能对于多个';
DROP TABLE IF EXISTS
    FC_INNERC_PAYMENT_CHANNEL;
CREATE
    TABLE FC_INNERC_PAYMENT_CHANNEL
    (
        PAYMENT_CHANNEL_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '支付渠道ID',
        CHANNEL_NAME VARCHAR(30) COLLATE utf8_bin COMMENT '渠道名称',
        PRIMARY KEY (PAYMENT_CHANNEL_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='支付渠道类型表(支付渠道表)';
DROP TABLE IF EXISTS
    FC_INNERC_PAYMENT_INFO;
CREATE
    TABLE FC_INNERC_PAYMENT_INFO
    (
        PAYMENT_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '第三方支付别名',
        PAYMENT_NAME VARCHAR(30) COLLATE utf8_bin COMMENT '第三方支付全称',
        PRIMARY KEY (PAYMENT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='第三方支付简码字典表(第三方支付简码字典)';
DROP TABLE IF EXISTS
    FC_LOAD_BANK_TRANS_FLOW;
CREATE
    TABLE FC_LOAD_BANK_TRANS_FLOW
    (
        BANK_TRANS_FLOW_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '银行充值交易流水ID',
        FC_DEPOSIT_APPLY_ID CHAR(38) COLLATE utf8_bin COMMENT '充值申请ID',
        PAY_DATE DATE NOT NULL COMMENT '支付日期',
        PAY_TIME TIME NOT NULL COMMENT '支付时间',
        TRANS_FLAG INT NOT NULL COMMENT '收付标志',
        BANK_FLOW_NO VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '银行流水号',
        SRC_BANK_ACCOUNT_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '支付账户',
        SRC_BANK_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '支付人姓名',
        AMOUNT DECIMAL(16,4) NOT NULL COMMENT '支付金额',
        CHARGE DECIMAL(16,4) NOT NULL COMMENT '手续费',
        SRC_BANK_TYPE VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '支付银行类型',
        SRC_BANK_BRANCH_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '开户行名称',
        SRC_BANK_BRANCH_NO VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '开户行号',
        BALANCE DECIMAL(16,4) NOT NULL COMMENT '账户余额',
        TRANSACTION_WAY VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '交易渠道',
        TRANSACTION_STATE INT NOT NULL COMMENT '交易状态',
        COMMENTS VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '附言',
        DEST_ACCOUNT_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '收款账户号',
        DEST_ACCOUNT_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '收款人姓名',
        DEST_BANK_TYPE VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '收款人银行类型',
        DEST_BANK_BRANCH_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '收款方开户行名',
        DEST_BANK_BRANCH_NO VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '开户行行号',
        CHECK_STATUS INT NOT NULL COMMENT '是否处理状态(0,默认值没有被勾兑，1已被勾兑，勾兑后不能再使用,2附言不匹配，付款卡匹配，3附言和卡都不匹配)',
        RECEIVE_TIME DATETIME NOT NULL COMMENT '接收时间(当前时间，设置为默认当前时间)',
        CHECK_TIME DATETIME NOT NULL COMMENT '勾兑时间',
        CHECK_COMMENTS VARCHAR(500) COLLATE utf8_bin COMMENT '勾兑备注',
        CHECK_TYPE INT NOT NULL COMMENT '勾兑类型(1,自动勾兑，2手工勾兑)',
        UPD_COMMENTS VARCHAR(100) COLLATE utf8_bin,
        PRIMARY KEY (BANK_TRANS_FLOW_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='银行充值交易流水表(客户充值的流水，银行流水)';
DROP TABLE IF EXISTS
    FC_LOAD_CHECK_OPERATE_RECORD;
CREATE
    TABLE FC_LOAD_CHECK_OPERATE_RECORD
    (
        LOAD_CHECK_OPERATE_RECORD_ID VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '手工勾兑记录表ID',
        CUSTOMER_EXCEPTION_RECORD_ID VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '充值异常登记ID',
        USER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
        CHECK_TYPE INT NOT NULL COMMENT '1, "一次勾兑" 2, "二次勾兑" 3, "异常挂起" ',
        CREATED_TIME DATETIME NOT NULL COMMENT '勾兑时间',
        COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '勾兑备注',
        PRIMARY KEY (LOAD_CHECK_OPERATE_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='手工勾兑记录表(手工勾兑相关操作记录，记录勾兑过程，最终勾兑后的结果写到关系表)';
DROP TABLE IF EXISTS
    FC_LOAD_CHECK_RECORD;
CREATE
    TABLE FC_LOAD_CHECK_RECORD
    (
        FC_LOAD_CHECK_RECORD_ID VARCHAR(64) COLLATE utf8_bin NOT NULL,
        CUSTOMER_EXCEPTION_RECORD_ID VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '充值异常登记ID',
        USER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
        BANK_TRANS_FLOW_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '银行充值交易流水ID',
        FC_DEPOSIT_APPLY_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '充值申请ID',
        CREATED_TIME DATETIME NOT NULL COMMENT '勾兑时间',
        COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '勾兑备注',
        PRIMARY KEY (FC_LOAD_CHECK_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='手工勾兑记录表(手工勾兑相关操作记录，记录勾兑过程，最终勾兑后的结果写到关系表)';
DROP TABLE IF EXISTS
    FC_LOAD_CUSTOMER_EXCEPTION_RECORD;
CREATE
    TABLE FC_LOAD_CUSTOMER_EXCEPTION_RECORD
    (
        CUSTOMER_EXCEPTION_RECORD_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '充值异常登记ID',
        USER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
        USER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '会员号',
        REAL_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '会员真实姓名',
        BANK_SERIAL_NO VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '银行流水号',
        BANK_TYPE VARCHAR(16) COLLATE utf8_bin NOT NULL COMMENT '银行类型',
        PAY_ACCOUNT_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '付款账号',
        PAYER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '付款名',
        PAY_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '汇款金额',
        PAY_TIME DATETIME NOT NULL COMMENT '汇款时间',
        RECEIPT_ACCOUNT_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '收款账号',
        RAW_COMMENT VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '原附言',
        CHANGED_COMMENT VARCHAR(32) COLLATE utf8_bin COMMENT '修改后附言',
        ATTACHMENT VARCHAR(200) COLLATE utf8_bin NOT NULL COMMENT '附件(附件地址)',
        SUSPEND_REASON VARCHAR(64) COLLATE utf8_bin COMMENT '挂起原因',
        PLATF_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '平台类型',
        DEAL_STATE INT NOT NULL COMMENT '处理状态(0 已上分 1挂起)',
        CREATED_TIME DATETIME NOT NULL COMMENT '异常登记时间',
        COMMENTS VARCHAR(512) COLLATE utf8_bin COMMENT '异常登记备注',
        PRIMARY KEY (CUSTOMER_EXCEPTION_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='充值异常登记表(用于客服人员登记会员提交的充值异常)';
DROP TABLE IF EXISTS
    FC_LOAD_DEPOSIT_APPLY;
CREATE
    TABLE FC_LOAD_DEPOSIT_APPLY
    (
        FC_DEPOSIT_APPLY_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '充值申请ID',
        DEPOSIT_APPLY_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '游戏平台充值申请流水号',
        USER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '会员账号',
        CHANNEL_TYPE INT NOT NULL COMMENT '充值渠道(1 银行 2第三方支付)',
        DEPOSIT_NO VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '充值账号',
        DEPOSIT_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '充值姓名',
        RECEIPT_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '收款账户',
        AGENT VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '代理',
        AMOUNT DECIMAL(16,4) NOT NULL COMMENT '申请充值金额',
        DEPOSIT_APPLY_TIME DATETIME NOT NULL COMMENT '充值申请时间',
        COMMENTS VARCHAR(128) COLLATE utf8_bin NOT NULL COMMENT '申请附言',
        RECEIVE_TIME DATETIME NOT NULL COMMENT '接收时间(当前时间，设置为默认当前时间)',
        STATUS INT NOT NULL COMMENT '处理状态(0，未处理，1已处理，2,已失效（假定3天失效）)',
        DATA_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '报文流水号(交易报文中的dataNo，返回时以这个为准)',
        BUSINESS_ID CHAR(38) COLLATE utf8_bin NOT NULL,
        CHANNEL_NAME VARCHAR(50) COLLATE utf8_bin,
        PRIMARY KEY (FC_DEPOSIT_APPLY_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='充值申请表(业务平台发送充值申请到充提平台)';
DROP TABLE IF EXISTS
    FC_LOAD_PAYMENT_TRANS_FLOW;
CREATE
    TABLE FC_LOAD_PAYMENT_TRANS_FLOW
    (
        PAYMENT_TRANS_FLOW_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '第三方充值交易流水ID',
        PAYMENT_FLOW_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '第三方充值订单',
        PAYER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '支付人姓名',
        PAY_ACCOUNT_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '支付账户',
        PAY_TIME DATETIME NOT NULL COMMENT '支付时间',
        PAY_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '支付金额',
        CHARGE DECIMAL(16,4) NOT NULL COMMENT '手续费',
        RECEIPT_ACCOUNT_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '收款账户号',
        PRIMARY KEY (PAYMENT_TRANS_FLOW_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='第三方充值交易流水表(客户通过第三方支付充值的流水)';
DROP TABLE IF EXISTS
    FC_LOAD_RECORD;
CREATE
    TABLE FC_LOAD_RECORD
    (
        LOAD_RECORD_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '充值上分记录',
        BUSINESS_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '平台编码',
        FC_DEPOSIT_APPLY_ID CHAR(38) COLLATE utf8_bin COMMENT '充值申请ID',
        USER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '会员账号',
        STATUS INT NOT NULL COMMENT '上分状态(0未上分，1已上分，2上分失败)，写入时间时为未上分',
        AMOUNT DECIMAL(16,4) NOT NULL COMMENT '充值金额(以银行流水合计为准，参考充值申请与银行流水关系表)',
        CHARGE DECIMAL(16,4) NOT NULL COMMENT '手续费(以银行流水中的手续费合计为准，参考充值申请与银行流水关系表)',
        COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '上分结果描述（游戏平台返回）',
        ADD_TIME DATETIME COMMENT '上分处理时间（游戏平台返回的时间）',
        ADD_TYPE INT NOT NULL COMMENT '上分类别(0 自动上分、1 手工勾兑上分、2异常人工上分（无银行交易记录，暂不考虑）)',
        DEAL_STATUS INT COMMENT '处理状态(0未处理，1处理中（已发送游戏平台未返回结果），2已处理)',
        CREATED_TIME DATETIME NOT NULL,
        LOAD_DESC VARCHAR(512) COLLATE utf8_bin COMMENT '勾兑结果的描述，失败需要说明',
        LOAD_STATUS INT NOT NULL COMMENT '1成功 0失败',
        PRIMARY KEY (LOAD_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='充值上分记录表(充值上分成功记录，数据字段参考充值上分接口字段，上分数据有三个来源，自动上分、手工勾兑上分和异常人工上分';
DROP TABLE IF EXISTS
    FC_NOTICE_NEW;
CREATE
    TABLE FC_NOTICE_NEW
    (
        NOTICE_ID CHAR(38) COLLATE utf8_bin NOT NULL,
        NOTICE_TITLE VARCHAR(200) COLLATE utf8_bin NOT NULL COMMENT '新闻标题',
        NOTICE_CONTENT VARCHAR(10240) COLLATE utf8_bin NOT NULL,
        STATUS INT COMMENT '1有效0无效',
        NOTICE_TYPE_ID CHAR(38) COLLATE utf8_bin,
        PUBLISHER CHAR(38) COLLATE utf8_bin COMMENT '用户ID',
        CREATED_TIME DATETIME,
        SHOW_START_TIME DATETIME,
        SHOW_END_TIME DATETIME,
        PRIMARY KEY (NOTICE_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='发布通知公告';
DROP TABLE IF EXISTS
    FC_NOTICE_TYPE;
CREATE
    TABLE FC_NOTICE_TYPE
    (
        NOTICE_TYPE_ID CHAR(38) COLLATE utf8_bin NOT NULL,
        NOTICE_TYPE_NAME VARCHAR(200) COLLATE utf8_bin NOT NULL COMMENT '类别名称',
        OPERATOR CHAR(38) COLLATE utf8_bin COMMENT '用户ID',
        CREATED_TIME DATETIME,
        PRIMARY KEY (NOTICE_TYPE_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_PAY_CUST_ORDER_DETAILS;
CREATE
    TABLE FC_PAY_CUST_ORDER_DETAILS
    (
        ORDER_DETAILS_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT 'UUID',
        FC_MESSAGE_NO CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '发送命令号',
        ORDER_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '订单号',
        ORDER_AMOUNT VARCHAR(18) COLLATE utf8_bin COMMENT '订单明细金额',
        DISPLAY_NAME VARCHAR(128) COLLATE utf8_bin COMMENT '下单商户显示名',
        GOODS_NAME VARCHAR(256) COLLATE utf8_bin COMMENT '商品名称',
        GOODS_COUNT VARCHAR(15) COLLATE utf8_bin COMMENT '商品数量',
        PRIMARY KEY (ORDER_DETAILS_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_PAY_FROM_CUSTOMER;
CREATE
    TABLE FC_PAY_FROM_CUSTOMER
    (
        FC_MESSAGE_NO CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '发送命令号',
        SERIAL_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '來自客戶的ID',
        NOTICE_URL VARCHAR(256) COLLATE utf8_bin COMMENT '商户通知地址',
        RETURN_URL VARCHAR(256) COLLATE utf8_bin COMMENT '商户回调地址',
        TOTAL_AMOUNT VARCHAR(18) COLLATE utf8_bin COMMENT '订单总金额',
        SUBMIT_TIME VARCHAR(14) COLLATE utf8_bin COMMENT '订单提交时间',
        ORG_CODE VARCHAR(12) COLLATE utf8_bin COMMENT '目标资金机构代码',
        REMARK VARCHAR(256) COLLATE utf8_bin COMMENT '扩展字段',
        PLATFORM_ID VARCHAR(32) COLLATE utf8_bin COMMENT '平台商 ID',
        HASH_TYPE VARCHAR(2) COLLATE utf8_bin COMMENT '签名类型',
        HASH VARCHAR(256) COLLATE utf8_bin COMMENT '签名字符串',
        PRIMARY KEY (FC_MESSAGE_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_PAY_FROM_NEWPAY;
CREATE
    TABLE FC_PAY_FROM_NEWPAY
    (
        FC_ORDER_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '給新生的ID',
        RESULT_CODE VARCHAR(4) COLLATE utf8_bin COMMENT '处理结果码',
        STATE_CODE VARCHAR(2) COLLATE utf8_bin COMMENT '状态码',
        ORDER_AMOUNT VARCHAR(18) COLLATE utf8_bin COMMENT '商户订单金额',
        PAY_AMOUNT VARCHAR(18) COLLATE utf8_bin COMMENT '实际支付金额',
        ACQUIRING_TIME VARCHAR(14) COLLATE utf8_bin COMMENT '收单时间',
        COMPLETE_TIME VARCHAR(14) COLLATE utf8_bin COMMENT '处理完成时间',
        ORDER_NO VARCHAR(32) COLLATE utf8_bin COMMENT '第三方支付的流水号',
        PARTNER_ID VARCHAR(32) COLLATE utf8_bin COMMENT '商户 ID',
        REMARK VARCHAR(256) COLLATE utf8_bin COMMENT '扩展字段',
        CHARSET VARCHAR(1) COLLATE utf8_bin COMMENT '编码方式',
        SIGN_TYPE VARCHAR(1) COLLATE utf8_bin COMMENT '签名类型',
        SIGN_MSG VARCHAR(256) COLLATE utf8_bin COMMENT '签名字符串',
        PRIMARY KEY (FC_ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_PAY_ORDER;
CREATE
    TABLE FC_PAY_ORDER
    (
        FC_MESSAGE_NO CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '发送命令号',
        FC_ORDER_PLATFORM VARCHAR(10) COLLATE utf8_bin,
        TOTAL_AMOUNT VARCHAR(18) COLLATE utf8_bin COMMENT '订单总金额',
        PARTNER_ID VARCHAR(32) COLLATE utf8_bin COMMENT '商户 ID ',
        NOTICE_URL VARCHAR(256) COLLATE utf8_bin COMMENT '商户通知地址',
        CHARSET VARCHAR(1) COLLATE utf8_bin COMMENT '编码方式 (1：UTF-8)',
        REMARK VARCHAR(256) COLLATE utf8_bin COMMENT '扩展字段',
        SIGN_TYPE VARCHAR(1) COLLATE utf8_bin COMMENT '签名类型(1：RSA 方式 2：MD5 方式)',
        SIGN_MSG VARCHAR(256) COLLATE utf8_bin COMMENT '签名字符串',
        RETURN_URL VARCHAR(256) COLLATE utf8_bin COMMENT '商户回调地址',
        PLATFORM_ID VARCHAR(32) COLLATE utf8_bin COMMENT '平台商 ID ',
        PRIMARY KEY (FC_MESSAGE_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_PAY_ORDER_DETAILS;
CREATE
    TABLE FC_PAY_ORDER_DETAILS
    (
        FC_ORDER_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '給新生的ID',
        FC_MESSAGE_NO CHAR(38) COLLATE utf8_bin COMMENT '发送命令号',
        ORDER_AMOUNT VARCHAR(18) COLLATE utf8_bin COMMENT '订单明细金额',
        DISPLAY_NAME VARCHAR(128) COLLATE utf8_bin COMMENT '下单商户显示名',
        GOODS_NAME VARCHAR(256) COLLATE utf8_bin COMMENT '商品名称',
        GOODS_COUNT VARCHAR(15) COLLATE utf8_bin COMMENT '商品数量',
        PRIMARY KEY (FC_ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_PAY_TO_CUSTOMER;
CREATE
    TABLE FC_PAY_TO_CUSTOMER
    (
        SERIAL_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '客戶订单ID',
        STATE_CODE VARCHAR(2) COLLATE utf8_bin COMMENT '状态码',
        ORDER_AMOUNT VARCHAR(18) COLLATE utf8_bin COMMENT '商户订单金额',
        PAY_AMOUNT VARCHAR(18) COLLATE utf8_bin COMMENT '实际支付金额',
        COMPLETE_TIME VARCHAR(14) COLLATE utf8_bin COMMENT '处理完成时间',
        REMARK VARCHAR(256) COLLATE utf8_bin COMMENT '扩展字段',
        PLATFORM_ID VARCHAR(32) COLLATE utf8_bin,
        HASH VARCHAR(256) COLLATE utf8_bin,
        HASH_TYPE VARCHAR(1) COLLATE utf8_bin,
        PRIMARY KEY (SERIAL_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_PAY_TO_NEWPAY;
CREATE
    TABLE FC_PAY_TO_NEWPAY
    (
        FC_MESSAGE_NO CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '发送命令号',
        VERSION VARCHAR(4) COLLATE utf8_bin COMMENT '版本',
        SUBMIT_TIME VARCHAR(14) COLLATE utf8_bin COMMENT '订单提交时间',
        FAILURE_TIME VARCHAR(14) COLLATE utf8_bin COMMENT '订单失效时间',
        CUSTOMER_IP VARCHAR(128) COLLATE utf8_bin COMMENT '客户下单域名及 IP',
        ORDER_DETAILS VARCHAR(1024) COLLATE utf8_bin COMMENT '订单明细信息',
        TYPE VARCHAR(4) COLLATE utf8_bin COMMENT '交易类型',
        BUYER_MARKED VARCHAR(64) COLLATE utf8_bin COMMENT '付款方新生账户号',
        PAY_TYPE VARCHAR(128) COLLATE utf8_bin COMMENT '付款方支付方式',
        ORG_CODE VARCHAR(12) COLLATE utf8_bin COMMENT '目标资金机构代码',
        CURRENCY_CODE VARCHAR(1) COLLATE utf8_bin COMMENT '交易币种 ',
        DIRECT_FLAG VARCHAR(1) COLLATE utf8_bin COMMENT '是否直连',
        BORROWING_MARKED VARCHAR(1) COLLATE utf8_bin COMMENT '资金来源借贷标识',
        COUPON_FLAG VARCHAR(2) COLLATE utf8_bin COMMENT '优惠券标识',
        PRIMARY KEY (FC_MESSAGE_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_RISK_CUSTOMER_ACCOUNT_INFO;
CREATE
    TABLE FC_RISK_CUSTOMER_ACCOUNT_INFO
    (
        CUSTOMER_ACCOUNT_INFO_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '会员总账信息ID',
        BUSINESS_ID CHAR(64) COLLATE utf8_bin NOT NULL COMMENT '平台编码',
        CUSTOMER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '会员名',
        AGENT VARCHAR(32) COLLATE utf8_bin COMMENT '代理人',
        ACCOUNT_BALANCE DECIMAL(16,4) NOT NULL COMMENT '账户余额',
        BLOCKED_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '冻结金额',
        AVAILABLE_BALANCE DECIMAL(16,4) NOT NULL COMMENT '可用余额',
        GAME_BALANCE VARCHAR(500) COLLATE utf8_bin NOT NULL COMMENT '第三方游戏平台余额',
        REGISTER_DATE DATETIME COMMENT '注册日期',
        RECORD_DATA DATETIME COMMENT '记录生成时间',
        FC_WITH_APPLY_ID CHAR(38) COLLATE utf8_bin NOT NULL,
        QUERY_START_TIME DATETIME NOT NULL,
        QUERY_END_TIME DATETIME NOT NULL,
        PRIMARY KEY (CUSTOMER_ACCOUNT_INFO_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='会员总账信息表(会员总账信息)';
DROP TABLE IF EXISTS
    FC_RISK_GAME_FLOW_DETAIL;
CREATE
    TABLE FC_RISK_GAME_FLOW_DETAIL
    (
        GAME_FLOW_DETAIL_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '游戏流水明细ID',
        BUSINESS_ID CHAR(64) COLLATE utf8_bin NOT NULL COMMENT '平台编码',
        FC_WITH_APPLY_ID CHAR(38) COLLATE utf8_bin COMMENT '提现申请ID',
        GAME_RECORD_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '游戏平台流水ID',
        GAME_CHANGE_TIME DATETIME NOT NULL COMMENT '账变时间',
        CHANGE_TYPE VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '账变类型',
        GAME_TYPE VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '游戏类型',
        GAME_RULE VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '游戏玩法',
        GAME_ISSUE VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '投注期号',
        BET_PATTERN VARCHAR(1024) COLLATE utf8_bin COMMENT '投注方案',
        GAME_PATTERN VARCHAR(16) COLLATE utf8_bin NOT NULL COMMENT '投注模式',
        IN_COME DECIMAL(16,4) COMMENT '收入金额',
        PAY_AMOUNT DECIMAL(16,4) COMMENT '支出金额',
        AVAILABLE_AMOUNT DECIMAL(16,4) COMMENT '可用余额(暂无数据，保留)',
        IP_ADDRESS VARCHAR(32) COLLATE utf8_bin COMMENT '网络IP',
        COMMENTS VARCHAR(512) COLLATE utf8_bin COMMENT '备注',
        CUSTOMER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '会员名',
        RECORD_DATA DATETIME COMMENT '记录生成时间',
        QUERY_START_TIME DATETIME NOT NULL,
        QUERY_END_TIME DATETIME NOT NULL,
        PROJECT_ID VARCHAR(64) COLLATE utf8_bin COMMENT '方案ID',
        PRE_BALANCE DOUBLE COMMENT '帐变前 账户余额( C )',
        PRE_HOLD DOUBLE COMMENT '帐变前 冻结资金( D )',
        PRE_AVAILABLE DOUBLE COMMENT '帐变前 可用资金( E )',
        CHANNEL_BALANCE DOUBLE COMMENT '帐变后 帐户余额( C )',
        HOLD_BALANCE DOUBLE COMMENT '帐变后 冻结资金( D )',
        AVAILABLE_BALANCE DOUBLE COMMENT '帐变后 可用资金( E )',
        PRIMARY KEY (GAME_FLOW_DETAIL_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='游戏流水明细表(游戏流水明细)';
DROP TABLE IF EXISTS
    FC_RISK_GAME_WINNING_INFO;
CREATE
    TABLE FC_RISK_GAME_WINNING_INFO
    (
        GAME_WINNING_INFO_ID VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '游戏中奖信息ID',
        BUSINESS_ID CHAR(64) COLLATE utf8_bin NOT NULL COMMENT '平台编码',
        FC_WITH_APPLY_ID CHAR(38) COLLATE utf8_bin COMMENT '提现申请ID',
        GAME_RECORD_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '游戏中奖流水号',
        BET_TIME VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '下注时间',
        BET_CLOSED_TIME VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '封盘时间',
        GAME_DRAW_TIME VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '开奖时间',
        WINNING_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '中奖金额',
        BET_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '投注金额',
        DRAW_RATE DOUBLE(5,3) COMMENT '中奖比例',
        BET_DOUBLE INT NOT NULL COMMENT '投注倍数',
        DRAW_NO VARCHAR(1024) COLLATE utf8_bin NOT NULL COMMENT '开奖号码',
        WINNING_NO VARCHAR(1024) COLLATE utf8_bin NOT NULL COMMENT '中奖号码',
        GAME_TYPE VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '游戏类型',
        GAME_RULE VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '游戏玩法',
        BET_PATTERN VARCHAR(10240) COLLATE utf8_bin NOT NULL COMMENT '投注方案',
        GAME_PATTERN VARCHAR(16) COLLATE utf8_bin NOT NULL COMMENT '投注模式',
        IP_ADDRESS VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '网络IP',
        BET_RATE INT COMMENT '码数',
        COMMENTS VARCHAR(512) COLLATE utf8_bin COMMENT '备注信息',
        CUSTOMER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '会员名',
        RECORD_DATA DATETIME NOT NULL COMMENT '记录生成时间',
        QUERY_START_TIME DATETIME NOT NULL,
        QUERY_END_TIME DATETIME NOT NULL,
        ISSUE VARCHAR(50) COLLATE utf8_bin COMMENT '奖期',
        CODE_TYPE VARCHAR(50) COLLATE utf8_bin COMMENT '选号方式',
        SINGLE_PRICE DOUBLE COMMENT '单倍价格',
        MULTIPLE VARCHAR(50) COLLATE utf8_bin COMMENT '倍数',
        TOTAL_PRICE DOUBLE COMMENT '总共价格',
        LV_TOP_ID VARCHAR(64) COLLATE utf8_bin COMMENT '总代ID',
        LV_TOP_POINT VARCHAR(50) COLLATE utf8_bin COMMENT '总代返点',
        LV_PROXY_ID VARCHAR(64) COLLATE utf8_bin COMMENT '属所一代ID',
        DEDUCT_TIME DATETIME COMMENT '真实扣款时间',
        CANCEL_TIME DATETIME COMMENT '取消时间',
        IS_DEDUCT CHAR(1) COLLATE utf8_bin COMMENT '是否真实扣款(0:未真实扣款的;1:真实扣款)',
        IS_CANCEL CHAR(1) COLLATE utf8_bin COMMENT '收否撤单(未撤单;1:;2:)',
        IS_GET_PRIZE CHAR(1) COLLATE utf8_bin COMMENT '中奖判断(0:未判断;1:中奖;2:未知)',
        PRIZE_STATUS CHAR(1) COLLATE utf8_bin COMMENT '派奖状态(0:未派奖;1:已派奖)',
        ON_MODEL VARCHAR(50) COLLATE utf8_bin COMMENT '投注无返点或者有返点模式',
        PRIMARY KEY (GAME_WINNING_INFO_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='游戏中奖信息表(游戏中奖信息)';
DROP TABLE IF EXISTS
    FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO;
CREATE
    TABLE FC_RISK_PREPAID_ACCOUNT_CHANGE_INFO
    (
        PREPAID_ACCOUNT_CHANGE_INFO_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '充值账变信息ID',
        BUSINESS_ID CHAR(64) COLLATE utf8_bin NOT NULL COMMENT '平台编码',
        ACCOUNT_CHANGE_ID VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '充值账变流水号',
        ACCOUNT_CHANGE_TIME DATETIME NOT NULL COMMENT '账变时间',
        ACCOUNT_CHANGE_TYPE VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '账变类型',
        ACCOUNT_CHANGE_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '账变金额',
        AVAILABLE_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '可用余额',
        IP_ADDRESS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '网络地址',
        ACCOUNT_NO_REMARK VARCHAR(512) COLLATE utf8_bin COMMENT '卡号备注',
        LOAD_TYPE INT NOT NULL COMMENT '上分类型(0 自动上分 1 手动上分)',
        REMARK VARCHAR(512) COLLATE utf8_bin COMMENT '备注',
        CUSTOMER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '会员名',
        RECORD_DATA DATETIME NOT NULL COMMENT '记录生成时间',
        FC_WITH_APPLY_ID CHAR(38) COLLATE utf8_bin NOT NULL,
        QUERY_START_TIME DATETIME NOT NULL,
        QUERY_END_TIME DATETIME NOT NULL,
        PRIMARY KEY (PREPAID_ACCOUNT_CHANGE_INFO_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='充值账变信息表(充值账变信息)';
DROP TABLE IF EXISTS
    FC_RISK_SORT_RULE;
CREATE
    TABLE FC_RISK_SORT_RULE
    (
        RULE_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '规则ID',
        RULE_TYPE INT NOT NULL COMMENT '规则类型(0:比例；1::金额)',
        RULE_VALUE VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '规则值(比例按照100，金额按照[0,1000])',
        WORK_CENTER VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '工作中心',
        RULE_DESC VARCHAR(200) COLLATE utf8_bin COMMENT '规则描述',
        RULE_FLAG INT NOT NULL COMMENT '是否选择（0：no；1：yes）',
        OPERATE_TIME DATETIME NOT NULL,
        OPERATOR CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
        PRIMARY KEY (RULE_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='风控分配规则定义';
DROP TABLE IF EXISTS
    FC_RISK_WITHDRAW_CHECK;
CREATE
    TABLE FC_RISK_WITHDRAW_CHECK
    (
        FC_WITHDRAW_CHECK_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT 'ID',
        BUSINESS_ID CHAR(64) COLLATE utf8_bin NOT NULL COMMENT '平台编码',
        FC_WITH_APPLY_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '提现申请ID',
        PLATFORM_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '平台类型',
        CUSTOMER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '用户名',
        CHECK_TYPE INT NOT NULL COMMENT '审核类型(0 初审， 1复审)',
        CHECK_NAME INT COMMENT '审核名称(0 流水初审，1流水复审，2中奖初审，3中奖复审，4账变初始，5账变复审)',
        CHECK_TIME DATETIME NOT NULL COMMENT '审核时间',
        USER_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '审核用户名',
        CHECK_RESULT INT NOT NULL COMMENT '审核结果',
        CHECK_REMARK VARCHAR(320) COLLATE utf8_bin COMMENT '审核备注',
        PRIMARY KEY (FC_WITHDRAW_CHECK_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单审批记录表()';
DROP TABLE IF EXISTS
    FC_SHIFT_ACCOUNT_CHANGE_RECORD;
CREATE
    TABLE FC_SHIFT_ACCOUNT_CHANGE_RECORD
    (
        ACCOUNT_CHANGE_RECORD_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户交接班记录ID',
        USER_ID VARCHAR(64) COLLATE utf8_bin COMMENT '交接班操作员()',
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        UPLOAD_BEGIN_TIME DATETIME COMMENT '交接班开始时间(上卡时间)',
        UNLOAD_END_TIME DATETIME COMMENT '交接班结束时间(签退时，设置时间，卡一定选择在加载时间与卸载时间之间，同时状态有效)',
        ACCOUNT_BEGIN_BALANCE DECIMAL(16,4) COMMENT '帐户初始余额(交接班时读取内部账户表余额作为初始余额)',
        AUDIT_STATUS INT COMMENT '0上卡，1下卡，2对账完成',
        AUDIT_END_TIME DATETIME,
        COMMENTS VARCHAR(256) COLLATE utf8_bin,
        PRIMARY KEY (ACCOUNT_CHANGE_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='账户交接班记录表';
DROP TABLE IF EXISTS
    FC_SHIFT_ACCOUNT_DETAIL;
CREATE
    TABLE FC_SHIFT_ACCOUNT_DETAIL
    (
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        BEGIN_BALANCE DECIMAL(16,4) COMMENT '初始余额',
        TOTAL_INCOME DECIMAL(16,4) COMMENT '总收入',
        TOTAL_PAY DECIMAL(16,4) COMMENT '总支出',
        LAST_BALANCE DECIMAL(16,4) COMMENT '账户余额',
        UPT_DATETIME DATETIME COMMENT '账务变动时间',
        TRANS_OUT_COUNT INT COMMENT '转账条数',
        TRANS_IN_COUNT INT COMMENT '转入条数',
        PRIMARY KEY (ACCOUNT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='活动账户分户汇总表(记录各活动账户分户账的当期汇总信息，每个交接班为一个周期，与活动账户管理表中的活动账户一致，当发生交';
DROP TABLE IF EXISTS
    FC_SHIFT_ACCOUNT_STATUS_RECORD;
CREATE
    TABLE FC_SHIFT_ACCOUNT_STATUS_RECORD
    (
        ACCOUNT_STATUS_RECORD_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户状态记录表ID',
        ACCOUNT_CHANGE_RECORD_ID VARCHAR(64) COLLATE utf8_bin COMMENT '账户交接班记录ID',
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        STATUS INT COMMENT '账户状态(0 无效， 1 有效，2,冻结（冻结时卡不能使用），新增时默认为1)',
        CHANGE_REASON VARCHAR(200) COLLATE utf8_bin COMMENT '状态变化原因',
        CHANGE_TIME DATETIME COMMENT '状态变化时间',
        PRIMARY KEY (ACCOUNT_STATUS_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='账户状态记录表()';
DROP TABLE IF EXISTS
    FC_SHIFT_ACTIVE_ACCOUNT;
CREATE
    TABLE FC_SHIFT_ACTIVE_ACCOUNT
    (
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        STATUS INT NOT NULL COMMENT '卡是否有效(0 无效， 1 有效，2,冻结（冻结时卡不能使用），新增时默认为1)',
        IS_TRANSFERING INT NOT NULL COMMENT '交易状态(0  待启动; 1  未转账或转账完成; 2  转账锁定; 3  正在转账; 9  卡异常)',
        TRANSIT_UPDATED_TIME DATETIME NOT NULL COMMENT '交易状态变化时间',
        REMARK VARCHAR(200) COLLATE utf8_bin,
        PROCESS_ID VARCHAR(100) COLLATE utf8_bin,
        PRIMARY KEY (ACCOUNT_ALIAS)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='当前活动账户(记录已经发出的所有自动和手动的上分卡、出款卡、中转卡，卡登陆时在这里做登陆标记，表示卡可用，心跳监听卡记录';
DROP TABLE IF EXISTS
    FC_SHIFT_AUDIT_MONITOR;
CREATE
    TABLE FC_SHIFT_AUDIT_MONITOR
    (
        MONITOR_ID CHAR(38) COLLATE utf8_bin NOT NULL,
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        OPERATION_TYPE VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '操作类型：0余额查询，1明细查询，2平账，3转回，4登出',
        MESSAGE_NO VARCHAR(200) COLLATE utf8_bin NOT NULL COMMENT '消息编号对应表FC_BANKMSG_ACCOUNT_QUERY_RESULT里的交易序列号',
        STATUS INT NOT NULL COMMENT '显示完成为1，未完成为0',
        CREATED_TIME DATETIME NOT NULL,
        COMPLETED_TIME DATETIME,
        OPERATOR VARCHAR(64) COLLATE utf8_bin NOT NULL,
        FC_SHIFT_ACCOUNT_CHANGE_RECORD CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户交接班ID',
        VALUE CHAR(38) COLLATE utf8_bin COMMENT '结果值',
        PRIMARY KEY (MONITOR_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='对账表-保存各种操作类型的状态';
DROP TABLE IF EXISTS
    FC_SHIFT_BANK_TRANS_FLOW;
CREATE
    TABLE FC_SHIFT_BANK_TRANS_FLOW
    (
        BANK_TRANS_FLOW_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '银行交易明细ID',
        FC_ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        ACCOUNT_NO VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '账户号',
        ACCOUNT_ALIAS VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '卡号(别名)',
        TRANS_TIME DATETIME NOT NULL COMMENT '交易时间',
        TRANS_AMOUNT DECIMAL(16,4) NOT NULL COMMENT '存入金额',
        TRANFLAG INT NOT NULL COMMENT '收付标志(收付标志 0 收款 1 付款)',
        POUNDAGE DECIMAL(16,4) NOT NULL COMMENT '手续费',
        BALANCE DECIMAL(16,4) NOT NULL COMMENT '账户余额',
        DEST_ACCOUNT_NO VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '对方账号',
        DEST_ACCOUNT_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '对方姓名',
        BANK_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '对方银行别名',
        TRANSACTION_WAY VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '交易方式',
        COMMENTS VARCHAR(50) COLLATE utf8_bin COMMENT '摘要',
        TRANSACTIONSTATE INT NOT NULL COMMENT '交易状态(0支付失败，1 支付成功)',
        PRIMARY KEY (BANK_TRANS_FLOW_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='银行交易明细(出款卡、中转卡的交易明细（不含上分卡，上分卡交易明细在充值交易明细表中），交接班时，自动从网银导入的交易)';
DROP TABLE IF EXISTS
    FC_SHIFT_CHECK_LOAN_DETAIL;
CREATE
    TABLE FC_SHIFT_CHECK_LOAN_DETAIL
    (
        CHECK_RESULT_RECORD_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '核对结果记录ID',
        BANK_TRANS_FLOW_ID VARCHAR(64) COLLATE utf8_bin COMMENT '银行交易明细ID',
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        CHECK_TIME DATETIME COMMENT '核对时间',
        USER_NAME VARCHAR(32) COLLATE utf8_bin COMMENT '操作员',
        RESULT INT COMMENT '核对结果(0表示银行记录不存在（没有出款） ,1表示出款记录不存在（重复出款或出错款）)',
        ERROR_INFO VARCHAR(200) COLLATE utf8_bin COMMENT '错误描述',
        DIFF_BALANCE DECIMAL(16,4) COMMENT '差错金额(差错的金额，正数为我们欠客户的，负数为多出款，可能造成损失)',
        IS_DEALED TINYINT(1) COMMENT '是否处理完成',
        FC_ORDER_NO CHAR(64) COLLATE utf8_bin,
        PRIMARY KEY (CHECK_RESULT_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='出款核对结果记录(核对出款卡银行交易明细与充提平台内部账户明细账表核对的结果记录，应该是收付一致，出款通过银行交易明细的';
DROP TABLE IF EXISTS
    FC_SHIFT_GROUP_CHANGE_RECORD;
CREATE
    TABLE FC_SHIFT_GROUP_CHANGE_RECORD
    (
        GROUP_CHANGE_RECORD_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '账户组交接班记录ID',
        ACCOUNT_GROUP_ID CHAR(38) COLLATE utf8_bin COMMENT '账户组ID',
        UPLOAD_BEGIN_TIME DATETIME COMMENT '交接班开始时间(上卡时间)',
        UNLOAD_END_TIME DATETIME COMMENT '交接班结束时间(签退时，设置时间，卡一定选择在加载时间与卸载时间之间，同时状态有效)',
        USER_ID CHAR(38) COLLATE utf8_bin COMMENT '交接班操作员',
        BUSINESS_ID CHAR(64) COLLATE utf8_bin COMMENT '平台编码',
        ACCOUNT_TIER INT NOT NULL,
        PRIMARY KEY (GROUP_CHANGE_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_SHIFT_MAKE_BALANCE_RECORD;
CREATE
    TABLE FC_SHIFT_MAKE_BALANCE_RECORD
    (
        MAKE_BALANCE_RECORD_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '交接平差记录ID',
        DIFF_AMOUNT DECIMAL(16,4) COMMENT '平差金额',
        DEAL_TIME DATETIME COMMENT '平差时间',
        USER_NAME VARCHAR(32) COLLATE utf8_bin COMMENT '操作人',
        RESULT INT COMMENT '平差结果(0 失败，1成功)',
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin COMMENT '账户别名',
        ACCOUNT_CHANGE_RECORD_ID CHAR(38) COLLATE utf8_bin COMMENT '账户交接班记录ID',
        PRIMARY KEY (MAKE_BALANCE_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='交接平差记录(平差记录，平差后在内部账户分户账表中增加一条交易明细，手工帐，在修改账户余额)';
DROP TABLE IF EXISTS
    FC_SHIFT_MONITOR_ORDER;
CREATE
    TABLE FC_SHIFT_MONITOR_ORDER
    (
        MONITOR_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '指令监控ID',
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '卡别名',
        ORDER_TYPE INT(8) COMMENT '指令类型(0,登陆指令;1,测试1元指令)',
        CREATE_TIME DATETIME COMMENT '创建时间',
        COMPLETED_TIME DATETIME COMMENT '完成时间',
        OPERATOR VARCHAR(64) COLLATE utf8_bin COMMENT '操作员',
        ACCOUNT_CHANGE_RECORD_ID CHAR(38) COLLATE utf8_bin COMMENT '交接班ID',
        STATUS INT(8) COMMENT '完成状态0，未完成，1完成',
        MESSAGE_NO VARCHAR(200) COLLATE utf8_bin COMMENT '消息编号对应表FC_BANKMSG_ACCOUNT_QUERY_RESULT里的交易序列号',
        VALUE CHAR(38) COLLATE utf8_bin COMMENT '结果值',
        PRIMARY KEY (MONITOR_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='该表记录是监控 上卡时发送指令状态的表';
DROP TABLE IF EXISTS
    FC_SHIFT_RETURN_TRANS;
CREATE
    TABLE FC_SHIFT_RETURN_TRANS
    (
        FC_ORDER_NO CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '平台交易流水号(充提平台的转账操作视为与银行发起的一次交易，每次会生成一个流水号，此流水号为交易的唯一标识，也是发给网银助手的命令序列号)',
        PAY_BANK_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '付款账户编号',
        PAY_BANK_NO VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '付款行账号',
        PAY_USER_NAME VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '付款人用户名称',
        INCOME_BANK_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '收款账户编号',
        INCOME_BANK_NO VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '收款行账号',
        INCOME_USER_NAME VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '收款人用户名称',
        AMOUNT DECIMAL(16,4) NOT NULL COMMENT '付款金额',
        INCOME_BANK_CITY VARCHAR(10) COLLATE utf8_bin COMMENT '收款账号开户城市名',
        INCOME_BANK_NAME VARCHAR(20) COLLATE utf8_bin COMMENT '收款账号开户行名称',
        TRANSFER_TYPE INT NOT NULL COMMENT '转账类型',
        POUNDAGE DECIMAL(16,4) NOT NULL COMMENT '手续费',
        INCOME_USER_PHONE VARCHAR(20) COLLATE utf8_bin COMMENT '收款人手机号码',
        INCOME_CONTACTS VARCHAR(10) COLLATE utf8_bin COMMENT '收款联系人',
        ORDER_TIMES INT NOT NULL COMMENT '命令发送次数(每笔放款只进行固定次数发送，每次次数+1)',
        STATUS INT NOT NULL COMMENT '状态(1成功，0失败，2处理中)',
        TRANS_TIME DATETIME COMMENT '交易时间(网银返回的实际交易时间)',
        NOW_TIME DATETIME COMMENT '当前时间(记录产生时间，以后后续查询用)',
        OPERATOR VARCHAR(20) COLLATE utf8_bin COMMENT '操作员ID(如果是全自动放款，此字段为空，如果是半自动、异常处理、人工放款此字段为操作员Id)',
        BANK_COMMENTS VARCHAR(500) COLLATE utf8_bin COMMENT '银行交易结果描述',
        TRANS_COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '交易附言',
        PRIMARY KEY (FC_ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='交接班转回记录表(有转回记录时，要调用转账程序，完成转账)';
DROP TABLE IF EXISTS
    FC_SHIFT_SIGN_RECORD;
CREATE
    TABLE FC_SHIFT_SIGN_RECORD
    (
        SIGN_RECORD_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '签到签退ID',
        USER_ID CHAR(38) COLLATE utf8_bin COMMENT '用户ID',
        SIGN_IN_TIME DATETIME COMMENT '签到时间',
        SIGN_OUT_TIME DATETIME COMMENT '签退时间',
        IS_BALANCE INT COMMENT '是否平账',
        IS_NORMAL_SIGN_IN INT COMMENT '是否正常签到',
        IS_NORMAL_SIGN_OUT INT COMMENT '是否正常签退',
        ACCOUNT_ID INT COMMENT '账户ID',
        OPERATOR_ID VARCHAR(64) COLLATE utf8_bin COMMENT '签退审核操作员(外键)',
        CHECK_TIME DATETIME COMMENT '审核时间',
        ACCOUNT_ALIAS VARCHAR(38) COLLATE utf8_bin,
        PRIMARY KEY (SIGN_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='签到签退表(交接班管理记录,签到签退记录)';
DROP TABLE IF EXISTS
    FC_SYS_BRANCH;
CREATE
    TABLE FC_SYS_BRANCH
    (
        BRANCH_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '机构ID(按层级编码，三位一级，100开头，顺序递增，有系统自动控制)',
        BRANCH_NAME VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '机构名称',
        BRANCH_DESC VARCHAR(200) COLLATE utf8_bin COMMENT '机构描述',
        BRANCH_MANAGER VARCHAR(50) COLLATE utf8_bin COMMENT '机构负责人',
        MOBILE VARCHAR(20) COLLATE utf8_bin COMMENT '机构负责人电话',
        BEGIN_TIME DATETIME COMMENT '有效开始时间',
        END_TIME DATETIME COMMENT '有效截止时间',
        PARENT_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '机构上一级ID',
        LEAF_FLAG INT(1) NOT NULL COMMENT '是否叶子节点，1是，0不是',
        BRANCH_SEQ INT NOT NULL COMMENT '同级机构顺序',
        LEVEL INT NOT NULL COMMENT '层级',
        PRIMARY KEY (BRANCH_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='机构表(机构表)';
DROP TABLE IF EXISTS
    FC_SYS_BUSINESS;
CREATE
    TABLE FC_SYS_BUSINESS
    (
        BUSINESS_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '平台编码',
        BUSINESS_NAME VARCHAR(100) COLLATE utf8_bin NOT NULL,
        BUSINESS_DESC VARCHAR(100) COLLATE utf8_bin,
        BUSINESS_MANAGER VARCHAR(100) COLLATE utf8_bin NOT NULL,
        BUSINESS_MOBILE VARCHAR(100) COLLATE utf8_bin,
        BUSINESS_SEQ INT NOT NULL,
        BEGIN_TIME DATETIME,
        END_TIME DATETIME,
        STATUS INT NOT NULL,
        BUSINESS_DATA_PERMISSION INT NOT NULL COMMENT '系统分配值，从1,2,4,8,16,32.。。。。',
        BUSINESS_SYSKEY VARCHAR(64) COLLATE utf8_bin,
        BUSINESS_IPADDRESS VARCHAR(128) COLLATE utf8_bin,
        BUSINESS_IFACE VARCHAR(40) COLLATE utf8_bin,
        PRIMARY KEY (BUSINESS_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='业务平台表';
DROP TABLE IF EXISTS
    FC_SYS_MENU;
CREATE
    TABLE FC_SYS_MENU
    (
        MENU_ID INT NOT NULL COMMENT '菜单ID',
        MENU_NAME VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '菜单名称',
        MENU_DESC VARCHAR(200) COLLATE utf8_bin COMMENT '菜单描述',
        MENU_SEQ INT DEFAULT '0' NOT NULL COMMENT '菜单顺序',
        MENU_URL VARCHAR(200) COLLATE utf8_bin NOT NULL COMMENT '菜单地址',
        PARENT_ID INT NOT NULL COMMENT '上级菜单ID',
        LEAF_FLAG INT NOT NULL COMMENT '是否叶子节点',
        LEVEL INT NOT NULL COMMENT '层级',
        ICON VARCHAR(50) COLLATE utf8_bin,
        PRIMARY KEY (MENU_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='菜单表(菜单表)';
DROP TABLE IF EXISTS
    FC_SYS_PARAMETER;
CREATE
    TABLE FC_SYS_PARAMETER
    (
        PARAMETER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '参数ID',
        PARAMETER_TYPE_ID CHAR(38) COLLATE utf8_bin COMMENT '参数类型ID',
        PARAMETER_MODEL VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '充值，提现等（load,withdraw,admin,process)',
        PARAMETER_CODE VARCHAR(20) COLLATE utf8_bin NOT NULL,
        PARAMETER_NAME VARCHAR(100) COLLATE utf8_bin NOT NULL,
        PARAMETER_VALUE VARCHAR(50) COLLATE utf8_bin NOT NULL,
        PARAMETER_VALUE_TYPE INT NOT NULL COMMENT '1字符2整数3时间',
        CREATED_TIME DATETIME NOT NULL,
        OPERATOR CHAR(38) COLLATE utf8_bin NOT NULL,
        UPDATED_TIME DATETIME,
        UPDATOR CHAR(38) COLLATE utf8_bin,
        REMARK VARCHAR(100) COLLATE utf8_bin,
        PRIMARY KEY (PARAMETER_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统参数表';
DROP TABLE IF EXISTS
    FC_SYS_PARAMETER_TYPE;
CREATE
    TABLE FC_SYS_PARAMETER_TYPE
    (
        PARAMETER_TYPE_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '参数ID',
        PARAMETER_TYPE_NAME VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '1技术参数，2业务参数，3流程参数',
        CREATED_TIME DATETIME NOT NULL,
        OPERATOR CHAR(38) COLLATE utf8_bin NOT NULL,
        UPDATED_TIME DATETIME,
        UPDATOR CHAR(38) COLLATE utf8_bin,
        REMARK VARCHAR(100) COLLATE utf8_bin,
        PRIMARY KEY (PARAMETER_TYPE_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统参数类型';
DROP TABLE IF EXISTS
    FC_SYS_ROLE;
CREATE
    TABLE FC_SYS_ROLE
    (
        ROLE_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '角色ID',
        ROLE_NAME VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '角色名称',
        ROLE_DESC VARCHAR(100) COLLATE utf8_bin COMMENT '角色权限描述',
        STATUS INT NOT NULL COMMENT '角色状态',
        ROLE_ICON VARCHAR(100) COLLATE utf8_bin,
        PROCESS_ROLE VARCHAR(50) COLLATE utf8_bin,
        ROLE_TYPE CHAR(1) COLLATE utf8_bin NOT NULL,
        IS_ACCOUNT_ROLE CHAR(1) COLLATE utf8_bin,
        PRIMARY KEY (ROLE_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色表(角色表)';
DROP TABLE IF EXISTS
    FC_SYS_ROLE_MENU;
CREATE
    TABLE FC_SYS_ROLE_MENU
    (
        ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '角色权限表ID',
        MENU_ID INT COMMENT '菜单ID',
        ROLE_ID CHAR(38) COLLATE utf8_bin COMMENT '角色ID',
        STATUS INT NOT NULL COMMENT '状态，采用统一状态字典',
        PRIMARY KEY (ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色权限表(角色权限表)';
DROP TABLE IF EXISTS
    FC_SYS_ROLE_MUTEX;
CREATE
    TABLE FC_SYS_ROLE_MUTEX
    (
        ROLE_MUTEX_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '角色互斥ID',
        ROLE_ID_A CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '角色ID',
        ROLE_ID_B CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '角色ID',
        STATUS INT NOT NULL COMMENT '状态',
        PRIMARY KEY (ROLE_MUTEX_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色互斥表(角色互斥表)';
DROP TABLE IF EXISTS
    FC_SYS_USER;
CREATE
    TABLE FC_SYS_USER
    (
        USER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
        BRANCH_ID VARCHAR(64) COLLATE utf8_bin NOT NULL COMMENT '机构ID(按层级编码，三位一级，100开头，顺序递增，有系统自动控制)',
        LOGIN_NAME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '登录名',
        USER_NAME VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '用户名称',
        MOBILE VARCHAR(20) COLLATE utf8_bin COMMENT '用户手机',
        USER_WORKADDRESS VARCHAR(100) COLLATE utf8_bin COMMENT '用户办公地址',
        STATUS INT NOT NULL COMMENT '用户状态',
        PASSWORD VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '用户系统密码(md5加密处理)',
        UPDATE_TIME DATETIME NOT NULL COMMENT '变更时间',
        CREATE_TIME DATETIME NOT NULL COMMENT '注册时间',
        CREATED_BY VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '注册人(取登录名称（用户的唯一名称）)',
        MODIFIED_BY VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '修改人',
        EMAIL VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT 'EMAIL',
        DATA_ENVIRON INT NOT NULL COMMENT '数据范围权限(现在只有平台权限)',
        ICON VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '用户头像图标',
        WORK_CENTER CHAR(38) COLLATE utf8_bin,
        PRIMARY KEY (USER_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表(用户表)';
DROP TABLE IF EXISTS
    FC_SYS_USER_ROLE;
CREATE
    TABLE FC_SYS_USER_ROLE
    (
        USER_ROLE_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '用户与角色关系ID',
        ROLE_ID VARCHAR(64) COLLATE utf8_bin COMMENT '角色ID',
        USER_ID CHAR(38) COLLATE utf8_bin COMMENT '用户ID',
        STATUS TINYINT COMMENT '状态',
        PRIMARY KEY (USER_ROLE_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户与角色关系表(用户与角色)';
DROP TABLE IF EXISTS
    FC_WEB_GAME_DATA;
CREATE
    TABLE FC_WEB_GAME_DATA
    (
        DATA_ID VARCHAR(64) COLLATE utf8_bin NOT NULL,
        DATA_TYPE VARCHAR(32) COLLATE utf8_bin,
        DATA_MSG_CONTENT VARCHAR(1500) COLLATE utf8_bin,
        DATA_MSG_CREATE_TIME VARCHAR(32) COLLATE utf8_bin,
        DATA_MSG_STATUS VARCHAR(11) COLLATE utf8_bin COMMENT '0-正常',
        DATA_MSG_UPDATE_TIME VARCHAR(32) COLLATE utf8_bin,
        DATA_MSG_PLATFROM VARCHAR(4) COLLATE utf8_bin,
        DATA_MSG_RESERVE1 VARCHAR(256) COLLATE utf8_bin,
        DATA_MSG_RESERVE2 VARCHAR(200) COLLATE utf8_bin,
        PRIMARY KEY (DATA_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='接口数据包括, 帐变明细, 流水明细, 中奖明细, 会员总帐信息.';
DROP TABLE IF EXISTS
    FC_WEB_GAME_RESULT;
CREATE
    TABLE FC_WEB_GAME_RESULT
    (
        RESULT_ID VARCHAR(32) COLLATE utf8_bin NOT NULL,
        RESULT_SMESSAGE_NO VARCHAR(64) COLLATE utf8_bin NOT NULL,
        RESULT_SERVICE_CODE VARCHAR(16) COLLATE utf8_bin NOT NULL,
        RESULT_SERVICE_TYPE VARCHAR(8) COLLATE utf8_bin NOT NULL,
        RESULT_SYSPLAT_CODE VARCHAR(8) COLLATE utf8_bin NOT NULL,
        RESULT_SEND_TIME DATETIME NOT NULL,
        RESULT_EXT_TIME VARCHAR(32) COLLATE utf8_bin NOT NULL,
        RESULT_DATA_NO VARCHAR(64) COLLATE utf8_bin NOT NULL,
        RESULT_STATUS VARCHAR(8) COLLATE utf8_bin,
        RESULT_ERROR_NO VARCHAR(8) COLLATE utf8_bin,
        RESULT_ERROR_MSG VARCHAR(128) COLLATE utf8_bin,
        RESULT_RESERVED1 VARCHAR(128) COLLATE utf8_bin,
        RESULT_RESERVED2 VARCHAR(128) COLLATE utf8_bin,
        PRIMARY KEY (RESULT_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_WEB_GAME_TRADE;
CREATE
    TABLE FC_WEB_GAME_TRADE
    (
        TRAD_ID VARCHAR(32) COLLATE utf8_bin NOT NULL,
        TRAD_TYPE VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '交易类型',
        TRAD_MSG_CONTENT VARCHAR(1800) COLLATE utf8_bin NOT NULL,
        TRAD_MSG_CREATE_TIME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '入库时间',
        TRAD_MSG_STATUS VARCHAR(4) COLLATE utf8_bin NOT NULL COMMENT '报文状态',
        TRAD_MSG_UPDATE_TIME VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '报文修改',
        TRAD_MSG_PLATFROM VARCHAR(4) COLLATE utf8_bin NOT NULL COMMENT '游戏平台,恒彩-hc,信彩-xc,博彩-bc',
        TRAD_MSG_RESERVE1 VARCHAR(128) COLLATE utf8_bin,
        TRAD_MSG_RESERVE2 VARCHAR(128) COLLATE utf8_bin,
        PRIMARY KEY (TRAD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='充提与游戏交易';
DROP TABLE IF EXISTS
    FC_WITHDRAW_APPLY;
CREATE
    TABLE FC_WITHDRAW_APPLY
    (
        FC_WITH_APPLY_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '提现申请ID',
        BUSINESS_ID CHAR(64) COLLATE utf8_bin NOT NULL COMMENT '平台编码',
        DRAW_APPLY_ID VARCHAR(30) COLLATE utf8_bin NOT NULL COMMENT '提款申请流水号(游戏平台提款申请流水号)',
        USER_NAME VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '会员账号',
        AMOUNT DECIMAL(16,4) NOT NULL COMMENT '提现金额',
        DRAW_TYPE VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '提现渠道(渠道类型字典表外键)',
        DRAW_BANK_ALIAS CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '提现卡银行别名',
        DRAW_NO VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '提现账号',
        DRAW_NAME VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '提现账号真实姓名',
        APPLY_TIME DATETIME NOT NULL COMMENT '提现申请时间',
        APPLY_RECEIVE_TIME DATETIME NOT NULL COMMENT '提现申请接收时间(充提平台收到提现申请的时间)',
        DATA_NO VARCHAR(32) COLLATE utf8_bin COMMENT '报文流水号(交易报文中的dataNo，返回时以这个为准)',
        RISK_STATUS INT COMMENT '风控数据状态(1未同步，2已同步，0同步失败，3风控审核，4风控通过，5风控不通过，6财务审核，7财务审核通过，8财务审核不通过)',
        STATUS INT COMMENT '(状态(1待提现，2提现中，3已提现，9提现未成功（查看提现备注）))',
        COMMENTS VARCHAR(300) COLLATE utf8_bin COMMENT '提现备注',
        RISK_SYN_TYPE INT COMMENT '风控数据同步失败类型(1.充提账变失败，2流水失败，4中奖数据失败，8总账数据失败，16获取用户信息失败)',
        RISK_SYN_STEP INT DEFAULT '0' NOT NULL,
        RISK_COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '风控数据备注，获取数据失败时用来说明原因',
        PRIMARY KEY (FC_WITH_APPLY_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='提现申请表(业务平台提现申请记录)';
DROP TABLE IF EXISTS
    FC_WITHDRAW_LOAN_APPLY_REF;
CREATE
    TABLE FC_WITHDRAW_LOAN_APPLY_REF
    (
        MAP_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '关联ID，无业务语义',
        LOAN_RECORD_ID CHAR(38) COLLATE utf8_bin COMMENT '放款ID',
        FC_WITH_APPLY_ID CHAR(38) COLLATE utf8_bin COMMENT '提现申请ID',
        PRIMARY KEY (MAP_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='放款申请关系表(申请与出款的关系表，申请和出款是多对一关系，1、直接出款和拆分出款：一次申请出款一次；2、合并出款：多次';
DROP TABLE IF EXISTS
    FC_WITHDRAW_LOAN_DETAIL;
CREATE
    TABLE FC_WITHDRAW_LOAN_DETAIL
    (
        FC_ORDER_NO CHAR(64) COLLATE utf8_bin NOT NULL COMMENT '平台交易流水号(充提平台的转账操作视为与银行发起的一次交易，每次会生成一个流水号，此流水号为交易的唯一标识，也是发给网银助手的命令序列号)',
        LOAN_RECORD_ID CHAR(38) COLLATE utf8_bin COMMENT '放款ID',
        PAY_BANK_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '付款行别名',
        PAY_BANK_NO VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '付款行账号',
        PAY_USER_NAME VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '付款人用户名称',
        INCOME_BANK_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '收款行别名',
        INCOME_BANK_NO VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '收款行账号',
        INCOME_USER_NAME VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '收款人用户名称',
        TRANS_COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '交易附言',
        AMOUNT DECIMAL(16,4) NOT NULL COMMENT '付款金额',
        INCOME_BANK_CITY VARCHAR(10) COLLATE utf8_bin COMMENT '收款账号开户城市名',
        INCOME_BANK_NAME VARCHAR(20) COLLATE utf8_bin COMMENT '收款账号开户行名称',
        TRANSFER_TYPE INT NOT NULL COMMENT '转账类型',
        POUNDAGE DECIMAL(16,4) COMMENT '手续费',
        INCOME_USER_PHONE VARCHAR(20) COLLATE utf8_bin COMMENT '收款人手机号码',
        INCOME_CONTACTS VARCHAR(10) COLLATE utf8_bin COMMENT '收款联系人',
        ORDER_TIMES INT NOT NULL COMMENT '命令发送次数(每笔放款只进行固定次数发送，每次次数+1)',
        STATUS INT COMMENT '放款状态(1转账中、2转账成功、9转账失败)',
        TRANS_TIME DATETIME COMMENT '交易时间(网银返回的实际交易时间)',
        CURRENTD_TIME DATETIME NOT NULL COMMENT '当前时间(记录产生时间，以后后续查询用)',
        OPERATOR VARCHAR(38) COLLATE utf8_bin NOT NULL COMMENT '操作员ID(如果是全自动放款，此字段为空，如果是半自动、异常处理、人工放款此字段为操作员Id)',
        BANK_COMMENTS VARCHAR(500) COLLATE utf8_bin COMMENT '银行交易结果描述',
        REMARK CHAR(100) COLLATE utf8_bin,
        AUDIT_FLAG INT,
        PRIMARY KEY (FC_ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='放款卡交易明细表(放款卡交易明细，提交放款任务时，记录此表，卡交易完成后修改此表状态)';
DROP TABLE IF EXISTS
    FC_WITHDRAW_LOAN_RECORD;
CREATE
    TABLE FC_WITHDRAW_LOAN_RECORD
    (
        LOAN_RECORD_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '放款ID',
        USER_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '操作员ID',
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        ACCOUNT_BANK_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '放款银行别名(取自银行别名字典表)',
        AMOUNT DECIMAL(16,4) NOT NULL COMMENT '放款金额',
        LOAN_TYPE INT NOT NULL COMMENT '放款类型(1全自动放款、2半自动放款、3异常处理、4人工放款)',
        LOAN_PATTERN INT NOT NULL COMMENT '放款模式(1单笔放款、2拆分放款、3合并放款)',
        LOAN_STATUS INT NOT NULL COMMENT '放款状态(1放款中、2放款成功、9放款失败)',
        LOAN_TIME DATETIME NOT NULL COMMENT '放款时间',
        COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '备注(放款状态描述，如放款失败原因等)',
        PRIMARY KEY (LOAN_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='放款表(放款记录表，流程到达放款任务前，根据金额自动生成不同模式任务，记录该表)';
DROP TABLE IF EXISTS
    FC_WITHDRAW_LOAN_TRANSIT_REF;
CREATE
    TABLE FC_WITHDRAW_LOAN_TRANSIT_REF
    (
        MAP_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '关联ID，无业务语义',
        FC_ORDER_NO CHAR(64) COLLATE utf8_bin COMMENT '平台交易流水号(充提平台的转账操作视为与银行发起的一次交易，每次会生成一个流水号，此流水号为交易的唯一标识，也是发给网银助手的命令序列号)',
        TRANSIT_RECORD_ID CHAR(38) COLLATE utf8_bin COMMENT '出款ID',
        PRIMARY KEY (MAP_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS
    FC_WITHDRAW_TRANSIT_DETAIL;
CREATE
    TABLE FC_WITHDRAW_TRANSIT_DETAIL
    (
        FC_ORDER_NO CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '平台交易流水号(充提平台的转账操作视为与银行发起的一次交易，每次会生成一个流水号，此流水号为交易的唯一标识，也是发给网银助手的命令序列号)',
        TRANSIT_RECORD_ID CHAR(38) COLLATE utf8_bin COMMENT '出款ID',
        PAY_BANK_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '付款行别名',
        PAY_BANK_NO VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '付款行账号',
        PAY_USER_NAME VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '付款人用户名称',
        INCOME_BANK_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '收款行别名',
        INCOME_BANK_NO VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '收款行账号',
        TRANS_COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '交易附言',
        INCOME_USER_NAME VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '收款人用户名称',
        AMOUNT DECIMAL(16,4) NOT NULL COMMENT '付款金额',
        INCOME_BANK_CITY VARCHAR(10) COLLATE utf8_bin COMMENT '收款账号开户城市名',
        INCOME_BANK_NAME VARCHAR(20) COLLATE utf8_bin COMMENT '收款账号开户行名称',
        TRANSFER_TYPE INT NOT NULL COMMENT '转账类型',
        POUNDAGE DECIMAL(16,4) COMMENT '手续费',
        INCOME_USER_PHONE VARCHAR(20) COLLATE utf8_bin COMMENT '收款人手机号码',
        INCOME_CONTACTS VARCHAR(10) COLLATE utf8_bin COMMENT '收款联系人',
        ORDER_TIMES INT NOT NULL COMMENT '命令发送次数(每笔放款只进行固定次数发送，每次次数+1)',
        STATUS INT COMMENT '出款状态(1转账中、2转账成功、9转账失败)',
        TRANS_TIME DATETIME COMMENT '交易时间(网银返回的实际交易时间)',
        CURRENTD_TIME DATETIME COMMENT '当前时间(记录产生时间，以后后续查询用)',
        OPERATOR VARCHAR(38) COLLATE utf8_bin COMMENT '操作员ID(如果是全自动放款，此字段为空，如果是半自动、异常处理、人工放款此字段为操作员Id)',
        BANK_COMMENTS VARCHAR(500) COLLATE utf8_bin COMMENT '银行交易结果描述',
        REMARK CHAR(100) COLLATE utf8_bin,
        AUDIT_FLAG INT,
        PRIMARY KEY (FC_ORDER_NO)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='出款卡交易明细表(记录交易明细，提交出款任务时，记录此表，卡交易完成后修改此表状态)';
DROP TABLE IF EXISTS
    FC_WITHDRAW_TRANSIT_RECORD;
CREATE
    TABLE FC_WITHDRAW_TRANSIT_RECORD
    (
        TRANSIT_RECORD_ID CHAR(38) COLLATE utf8_bin NOT NULL COMMENT '出款ID',
        FC_WITH_APPLY_ID CHAR(38) COLLATE utf8_bin COMMENT '提现申请ID',
        ACCOUNT_ALIAS CHAR(38) COLLATE utf8_bin COMMENT '账户编号(内部用于方便记忆的编号，比如ICBC5, 与平台编号共同确保唯一号，要有规则)',
        ACCOUNT_BANK_ALIAS VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '出款银行别名(取自银行别名字典表)',
        AMOUNT DECIMAL(16,4) NOT NULL COMMENT '出款金额',
        OPERATOR CHAR(38) COLLATE utf8_bin DEFAULT 'NF' COMMENT '操作员ID(如果是全自动放款，此字段为NF，如果是半自动、异常处理、人工放款此字段为操作员Id)',
        TRANSIT_TYPE INT NOT NULL COMMENT '出款类型(1全自动放款、2半自动放款、3异常处理、4人工放款)',
        TRANSIT_PATTERN INT NOT NULL COMMENT '出款模式(1单笔放款、2拆分放款、3合并放款)',
        TRANSIT_STATUS INT NOT NULL COMMENT '出款状态(1放款中、2放款成功、9放款失败)',
        TRANSIT_TIME DATETIME NOT NULL COMMENT '出款时间',
        COMMENTS VARCHAR(200) COLLATE utf8_bin COMMENT '备注(放款状态描述，如放款失败原因等)',
        PRIMARY KEY (TRANSIT_RECORD_ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='出款表(出款记录表，流程到达出款任务前，根据金额自动生成不同模式任务，记录该表)';
