use fcpay;

DROP TABLE if exists FC_PAY_ORDER_RECORD;
CREATE
    TABLE FC_PAY_ORDER_RECORD
    (
        FC_RECORD_ID VARCHAR(64) COLLATE utf8_general_ci NOT NULL COMMENT '纪录流水号',
        FC_MESSAGE_NO CHAR(64) COLLATE utf8_general_ci NOT NULL COMMENT '发送命令号',
        ORDER_NO VARCHAR(38) COLLATE utf8_general_ci NOT NULL COMMENT '客户订单编号',
        STATE_CODE VARCHAR(2) COLLATE utf8_general_ci COMMENT '订单状态（ 0.未交易1. 处理中 2. 已交易3.交易失败)',
        SUBMIT_TIME DATETIME NOT NULL COMMENT '交易时间',
        COMPLATE_TIME DATETIME COMMENT '完成时间',
        COMMIT VARCHAR(255) COLLATE utf8_general_ci COMMENT '备注',
        LAST_UPDATE_TIME DATETIME NOT NULL COMMENT '最后修改时间',
        TYPE CHAR(2) COLLATE utf8_general_ci COMMENT '交易类型（ 1.支付2.退款）',
        REFUND_ID VARCHAR(38) COLLATE utf8_general_ci COMMENT '退款编号',
        ORDER_ID VARCHAR(38) COLLATE utf8_general_ci COMMENT '订单编号',
        TRADE_CHANNEL VARCHAR(32) COLLATE utf8_general_ci COMMENT '交易平台类型（新生支付，支付宝...... ）',
        PLATFORM_ID VARCHAR(32) COLLATE utf8_general_ci COMMENT '客戶平台',
        ORG_CODE VARCHAR(20) COMMENT '机构代码',
        REFUND_STATE_CODE VARCHAR(50) COMMENT '退款代码',
        REFUND_RECORD_NO VARCHAR(64) COMMENT '退款流水号',
        PAID_AMOUNT VARCHAR(8) COMMENT '支付金额',
        REFUND_AMOUNT VARCHAR(8) COMMENT '退款金额',
        CODE VARCHAR(100) COMMENT '代码',
        CODE_MSG VARCHAR(300) COMMENT '代码说明',
        PARTNER_ID VARCHAR(32) COMMENT '商户号',
        PRIMARY KEY (FC_RECORD_ID)
    ) DEFAULT CHARSET=utf8;
	

DROP TABLE if exists  FC_SYS_BUSINESS;
CREATE
    TABLE FC_SYS_BUSINESS
    (
        BUSINESS_ID CHAR(38) NOT NULL COMMENT '平台编码',
        BUSINESS_NAME VARCHAR(100) NOT NULL,
        BUSINESS_DESC VARCHAR(100),
        BUSINESS_MANAGER VARCHAR(100) NOT NULL,
        BUSINESS_MOBILE VARCHAR(100),
        BUSINESS_SEQ INT NOT NULL,
        BEGIN_TIME DATETIME,
        END_TIME DATETIME,
        STATUS INT NOT NULL,
        BUSINESS_DATA_PERMISSION INT NOT NULL COMMENT '系统分配值，从1,2,4,8,16,32.。。。。',
        BUSINESS_SYSKEY VARCHAR(64),
        BUSINESS_IPADDRESS VARCHAR(128),
        BUSINESS_IFACE VARCHAR(40),
        BUSINESS_PROCESS VARCHAR(100),
        PRIMARY KEY (BUSINESS_ID)
    ) DEFAULT CHARSET=utf8;


insert into FC_SYS_BUSINESS (BUSINESS_ID, BUSINESS_NAME, BUSINESS_DESC, BUSINESS_MANAGER, BUSINESS_MOBILE, BUSINESS_SEQ, BEGIN_TIME, END_TIME, STATUS, BUSINESS_DATA_PERMISSION, BUSINESS_SYSKEY, BUSINESS_IPADDRESS, BUSINESS_IFACE, BUSINESS_PROCESS) values ('LT', '论坛', '论坛', 'super', '0975656565', 2, null, null, 1, 4, '', '', '', '');

update FC_SYS_BUSINESS set BUSINESS_SYSKEY = '23F25C053E50988618F7E115B81772CFRS'  where BUSINESS_ID = 'LT';

